In [1]:
import pandas as pd

In [11]:
df = pd.read_csv(r"Fortune_10.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [13]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.shape

(10, 8)

In [17]:
df.ndim

2

In [19]:
df.size

80

In [29]:
df.head(5)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%

In [31]:
df.tail(5)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [35]:
df.describe()

              ID    Inception        Profit
count   8.000000    10.000000  1.000000e+01
mean    5.750000  2010.000000  6.379048e+06
std     3.370036     1.943651  3.267128e+06
min     1.000000  2006.000000  3.005116e+06
25%     2.750000  2009.000000  3.672608e+06
50%     6.500000  2010.000000  5.513445e+06
75%     8.250000  2011.000000  7.970251e+06
max    10.000000  2013.000000  1.190118e+07

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         8 non-null      float64
 1   Name       10 non-null     object
 2   Industry   8 non-null      object
 3   Inception  10 non-null     int64
 4   Revenue    9 non-null      object
 5   Expenses   9 non-null      object
 6   Profit     10 non-null     int64
 7   Growth     9 non-null      object
dtypes: float64(1), int64(2), object(5)
memory usage: 772.0+ bytes

In [44]:
df.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False     True     False   False   False
3   True  False      True      False    False     False   False   False
4   True  False      True      False    False      True   False   False
5  False  False     False      False    False     False   False    True
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False     False   False   False
9  False  False     False      False    False     False   False   False

In [46]:
df.isnull().sum()

ID           2
Name         0
Industry     2
Inception    0
Revenue      1
Expenses     1
Profit       0
Growth       1
dtype: int64

In [48]:
df.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [50]:
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [52]:
df.dropna(axis = 1)

              Name  Inception    Profit
0          Lamtone       2009   5274553
1        Stripfind       2010  11412916
2  Canecorporation       2012   3005820
3         Mattouch       2013   6597557
4        Techdrill       2009   3138627
5           Health       2006   8427816
6          Cityace       2010   3005116
7   Kayelectronics       2009   5573830
8          Ganzlax       2011  11901180
9      Trantraxlax       2011   5453060

In [58]:
df.dropna(how = "all")

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [70]:
df.dropna(thresh = 6)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [74]:
df.dropna(subset = "Revenue")

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [78]:
df.dropna(subset = [2], axis = 1)

,ID,Name,Industry,Inception,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,NaN,3138627,7%
5,6.0,Health,Health,2006,"5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"5,635,276 Dollars",5453060,7%

In [80]:
df.fillna(method = "bfill")

C:\Users\DHANANJAY\AppData\Local\Temp\ipykernel_28284\3988041702.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "bfill")

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$14,026,934","7,591,189 Dollars",3005820,7%
3,6.0,Mattouch,Health,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,6.0,Techdrill,Health,2009,"$10,573,990","5,470,303 Dollars",3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,16%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [82]:
df.fillna(method = "ffill")

C:\Users\DHANANJAY\AppData\Local\Temp\ipykernel_28284\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$12,329,371","7,591,189 Dollars",3005820,7%
3,3.0,Mattouch,Health,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,3.0,Techdrill,Health,2009,"$10,573,990","7,429,377 Dollars",3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,7%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [84]:
df.fillna(method = "ffill", limit = 1)

C:\Users\DHANANJAY\AppData\Local\Temp\ipykernel_28284\3782796259.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill", limit = 1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$12,329,371","7,591,189 Dollars",3005820,7%
3,3.0,Mattouch,Health,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990","7,429,377 Dollars",3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,7%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [102]:
df.replace(to_replace = '', value = 10)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,NaN,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,NaN,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [104]:
df.interpolate()

C:\Users\DHANANJAY\AppData\Local\Temp\ipykernel_28284\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,NaN,"7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,NaN,2013,"$14,026,934","7,429,377 Dollars",6597557,7%
4,5.0,Techdrill,NaN,2009,"$10,573,990",NaN,3138627,7%
5,6.0,Health,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,16%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%