In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

Raw Data → Data Understanding → Data Quality Assessment → Missing Value Handling → Outlier Treatment → Data Type Fixing → Feature Encoding & Scaling → Validation (Before vs After) → Clean Dataset → ML Model

# Method 2 - Rows first then Columns (filling nan values based on mean of different classes)

In [6]:
df = pd.read_csv("train.csv")
df.shape

(1460, 81)

In [7]:
df_null_clm = df.isnull().sum().to_frame("null count")
df_null_clm["null percentage"] = df_null_clm["null count"] / df.shape[0] * 100
df_null_clm

               null count  null percentage
Id                      0         0.000000
MSSubClass              0         0.000000
MSZoning                0         0.000000
LotFrontage           259        17.739726
LotArea                 0         0.000000
Street                  0         0.000000
Alley                1369        93.767123
LotShape                0         0.000000
LandContour             0         0.000000
Utilities               0         0.000000
LotConfig               0         0.000000
LandSlope               0         0.000000
Neighborhood            0         0.000000
Condition1              0         0.000000
Condition2              0         0.000000
BldgType                0         0.000000
HouseStyle              0         0.000000
OverallQual             0         0.000000
OverallCond             0         0.000000
YearBuilt               0         0.000000
YearRemodAdd            0         0.000000
RoofStyle               0         0.000000
RoofMatl                0         0.000000
Exterior1st             0         0.000000
Exterior2nd             0         0.000000
MasVnrType            872        59.726027
MasVnrArea              8         0.547945
ExterQual               0         0.000000
ExterCond               0         0.000000
Foundation              0         0.000000
BsmtQual               37         2.534247
BsmtCond               37         2.534247
BsmtExposure           38         2.602740
BsmtFinType1           37         2.534247
BsmtFinSF1              0         0.000000
BsmtFinType2           38         2.602740
BsmtFinSF2              0         0.000000
BsmtUnfSF               0         0.000000
TotalBsmtSF             0         0.000000
Heating                 0         0.000000
HeatingQC               0         0.000000
CentralAir              0         0.000000
Electrical              1         0.068493
1stFlrSF                0         0.000000
2ndFlrSF                0         0.000000
LowQualFinSF            0         0.000000
GrLivArea               0         0.000000
BsmtFullBath            0         0.000000
BsmtHalfBath            0         0.000000
FullBath                0         0.000000
HalfBath                0         0.000000
BedroomAbvGr            0         0.000000
KitchenAbvGr            0         0.000000
KitchenQual             0         0.000000
TotRmsAbvGrd            0         0.000000
Functional              0         0.000000
Fireplaces              0         0.000000
FireplaceQu           690        47.260274
GarageType             81         5.547945
GarageYrBlt            81         5.547945
GarageFinish           81         5.547945
GarageCars              0         0.000000
GarageArea              0         0.000000
GarageQual             81         5.547945
GarageCond             81         5.547945
PavedDrive              0         0.000000
WoodDeckSF              0         0.000000
OpenPorchSF             0         0.000000
EnclosedPorch           0         0.000000
3SsnPorch               0         0.000000
ScreenPorch             0         0.000000
PoolArea                0         0.000000
PoolQC               1453        99.520548
Fence                1179        80.753425
MiscFeature          1406        96.301370
MiscVal                 0         0.000000
MoSold                  0         0.000000
YrSold                  0         0.000000
SaleType                0         0.000000
SaleCondition           0         0.000000
SalePrice               0         0.000000

In [8]:
df_null_per = df_null_clm[df_null_clm["null percentage"] > 20]
df_null_per

             null count  null percentage
Alley              1369        93.767123
MasVnrType          872        59.726027
FireplaceQu         690        47.260274
PoolQC             1453        99.520548
Fence              1179        80.753425
MiscFeature        1406        96.301370

In [9]:
l = df_null_per.index
l

Index(['Alley', 'MasVnrType', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], dtype='object')

In [10]:
df_drop_clm = df.drop(columns = l)
df_drop_clm.shape

(1460, 75)

In [11]:
df_num = df_drop_clm.select_dtypes(include = ["int64", "float64"])
df_num.shape

(1460, 38)

In [12]:
df1 = df_num.isnull().sum() / df_num.shape[0] * 100
df1

Id                0.000000
MSSubClass        0.000000
LotFrontage      17.739726
LotArea           0.000000
OverallQual       0.000000
OverallCond       0.000000
YearBuilt         0.000000
YearRemodAdd      0.000000
MasVnrArea        0.547945
BsmtFinSF1        0.000000
BsmtFinSF2        0.000000
BsmtUnfSF         0.000000
TotalBsmtSF       0.000000
1stFlrSF          0.000000
2ndFlrSF          0.000000
LowQualFinSF      0.000000
GrLivArea         0.000000
BsmtFullBath      0.000000
BsmtHalfBath      0.000000
FullBath          0.000000
HalfBath          0.000000
BedroomAbvGr      0.000000
KitchenAbvGr      0.000000
TotRmsAbvGrd      0.000000
Fireplaces        0.000000
GarageYrBlt       5.547945
GarageCars        0.000000
GarageArea        0.000000
WoodDeckSF        0.000000
OpenPorchSF       0.000000
EnclosedPorch     0.000000
3SsnPorch         0.000000
ScreenPorch       0.000000
PoolArea          0.000000
MiscVal           0.000000
MoSold            0.000000
YrSold            0.000000
SalePrice         0.000000
dtype: float64

In [13]:
l1 = df1[df1 > 0].keys()
l1

Index(['LotFrontage', 'MasVnrArea', 'GarageYrBlt'], dtype='object')

In [14]:
l2 = df_drop_clm["LotConfig"].value_counts().keys()
l2

Index(['Inside', 'Corner', 'CulDSac', 'FR2', 'FR3'], dtype='object', name='LotConfig')

In [15]:
df_drop_clm.loc[df_drop_clm["LotConfig"] == "Inside", "LotFrontage" : "LotConfig"]

      LotFrontage  LotArea Street LotShape LandContour Utilities LotConfig
0            65.0     8450   Pave      Reg         Lvl    AllPub    Inside
2            68.0    11250   Pave      IR1         Lvl    AllPub    Inside
5            85.0    14115   Pave      IR1         Lvl    AllPub    Inside
6            75.0    10084   Pave      Reg         Lvl    AllPub    Inside
8            51.0     6120   Pave      Reg         Lvl    AllPub    Inside
10           70.0    11200   Pave      Reg         Lvl    AllPub    Inside
11           85.0    11924   Pave      IR1         Lvl    AllPub    Inside
12            NaN    12968   Pave      IR2         Lvl    AllPub    Inside
13           91.0    10652   Pave      IR1         Lvl    AllPub    Inside
17           72.0    10791   Pave      Reg         Lvl    AllPub    Inside
18           66.0    13695   Pave      Reg         Lvl    AllPub    Inside
19           70.0     7560   Pave      Reg         Lvl    AllPub    Inside
21           57.0     7449   Pave      Reg         Bnk    AllPub    Inside
22           75.0     9742   Pave      Reg         Lvl    AllPub    Inside
23           44.0     4224   Pave      Reg         Lvl    AllPub    Inside
24            NaN     8246   Pave      IR1         Lvl    AllPub    Inside
27           98.0    11478   Pave      Reg         Lvl    AllPub    Inside
29           60.0     6324   Pave      IR1         Lvl    AllPub    Inside
30           50.0     8500   Pave      Reg         Lvl    AllPub    Inside
33           70.0    10552   Pave      IR1         Lvl    AllPub    Inside
34           60.0     7313   Pave      Reg         Lvl    AllPub    Inside
35          108.0    13418   Pave      Reg         Lvl    AllPub    Inside
37           74.0     8532   Pave      Reg         Lvl    AllPub    Inside
38           68.0     7922   Pave      Reg         Lvl    AllPub    Inside
39           65.0     6040   Pave      Reg         Lvl    AllPub    Inside
40           84.0     8658   Pave      Reg         Lvl    AllPub    Inside
41          115.0    16905   Pave      Reg         Lvl    AllPub    Inside
44           70.0     7945   Pave      Reg         Lvl    AllPub    Inside
45           61.0     7658   Pave      Reg         Lvl    AllPub    Inside
47           84.0    11096   Pave      Reg         Lvl    AllPub    Inside
48           33.0     4456   Pave      Reg         Lvl    AllPub    Inside
49           66.0     7742   Pave      Reg         Lvl    AllPub    Inside
51           52.0     6240   Pave      Reg         Lvl    AllPub    Inside
53           68.0    50271   Pave      IR1         Low    AllPub    Inside
54           60.0     7134   Pave      Reg         Bnk    AllPub    Inside
55          100.0    10175   Pave      IR1         Lvl    AllPub    Inside
56           24.0     2645   Pave      Reg         Lvl    AllPub    Inside
59           60.0     7200   Pave      Reg         Bnk    AllPub    Inside
60           63.0    13072   Pave      Reg         Lvl    AllPub    Inside
61           60.0     7200   Pave      Reg         Lvl    AllPub    Inside
62           44.0     6442   Pave      IR1         Lvl    AllPub    Inside
63           50.0    10300   Pave      IR1         Bnk    AllPub    Inside
64            NaN     9375   Pave      Reg         Lvl    AllPub    Inside
65           76.0     9591   Pave      Reg         Lvl    AllPub    Inside
66            NaN    19900   Pave      Reg         Lvl    AllPub    Inside
67           72.0    10665   Pave      IR1         Lvl    AllPub    Inside
70           95.0    13651   Pave      IR1         Lvl    AllPub    Inside
73           85.0    10200   Pave      Reg         Lvl    AllPub    Inside
75           21.0     1596   Pave      Reg         Lvl    AllPub    Inside
76            NaN     8475   Pave      IR1         Lvl    AllPub    Inside
77           50.0     8635   Pave      Reg         Lvl    AllPub    Inside
78           72.0    10778   Pave      Reg         Lvl    AllPub    Inside
82           78.0    10206   Pave      Reg         Lvl    AllPub    Inside
83           80.0     8892   Pave      IR1         Lvl    AllPub    Inside
84            NaN     8530   Pave      IR1         Lvl    AllPub    Inside
86          122.0    11911   Pave      IR2         Lvl    AllPub    Inside
89           60.0     8070   Pave      Reg         Lvl    AllPub    Inside
90           60.0     7200   Pave      Reg         Lvl    AllPub    Inside
91           85.0     8500   Pave      Reg         Lvl    AllPub    Inside
92           80.0    13360   Pave      IR1         HLS    AllPub    Inside
94           69.0     9337   Pave      IR1         Lvl    AllPub    Inside
96           78.0    10264   Pave      IR1         Lvl    AllPub    Inside
97           73.0    10921   Pave      Reg         HLS    AllPub    Inside
99           77.0     9320   Pave      IR1         Lvl    AllPub    Inside
100           NaN    10603   Pave      IR1         Lvl    AllPub    Inside
101          77.0     9206   Pave      Reg         Lvl    AllPub    Inside
102          64.0     7018   Pave      Reg         Bnk    AllPub    Inside
105          75.0     9375   Pave      Reg         Lvl    AllPub    Inside
106          60.0    10800   Pave      Reg         Lvl    AllPub    Inside
107          50.0     6000   Pave      Reg         Lvl    AllPub    Inside
109         105.0    11751   Pave      IR1         Lvl    AllPub    Inside
110          75.0     9525   Pave      Reg         Lvl    AllPub    Inside
111           NaN     7750   Pave      IR1         Lvl    AllPub    Inside
112          77.0     9965   Pave      Reg         Lvl    AllPub    Inside
114          61.0     7259   Pave      IR1         Lvl    AllPub    Inside
116           NaN    11616   Pave      Reg         Lvl    AllPub    Inside
119          65.0     8461   Pave      Reg         Lvl    AllPub    Inside
121          50.0     6060   Pave      Reg         Lvl    AllPub    Inside
123          55.0     7892   Pave      Reg         Lvl    AllPub    Inside
125          60.0     6780   Pave      Reg         Lvl    AllPub    Inside
126           NaN     4928   Pave      IR1         Lvl    AllPub    Inside
127          55.0     4388   Pave      IR1         Bnk    AllPub    Inside
128          69.0     7590   Pave      Reg         Lvl    AllPub    Inside
129          69.0     8973   Pave      Reg         Lvl    AllPub    Inside
133           NaN     6853   Pave      IR1         Lvl    AllPub    Inside
134          78.0    10335   Pave      IR1         Lvl    AllPub    Inside
135          80.0    10400   Pave      Reg         Lvl    AllPub    Inside
137          82.0    11070   Pave      Reg         Lvl    AllPub    Inside
138          73.0     9066   Pave      IR1         Lvl    AllPub    Inside
139          65.0    15426   Pave      IR1         Lvl    AllPub    Inside
141          78.0    11645   Pave      Reg         Lvl    AllPub    Inside
143          78.0    10335   Pave      IR1         Lvl    AllPub    Inside
144          70.0     9100   Pave      Reg         Lvl    AllPub    Inside
145          24.0     2522   Pave      Reg         Lvl    AllPub    Inside
148          63.0     7500   Pave      Reg         Lvl    AllPub    Inside
149           NaN     6240   Pave      Reg         Lvl    AllPub    Inside
151         107.0    13891   Pave      Reg         Lvl    AllPub    Inside
153           NaN    13500   Pave      Reg         Lvl    AllPub    Inside
156          60.0     7200   Pave      Reg         Lvl    AllPub    Inside
161         110.0    13688   Pave      IR1         Lvl    AllPub    Inside
163          55.0     5500   Pave      Reg         Lvl    AllPub    Inside
165          62.0    10106   Pave      Reg         Lvl    AllPub    Inside
166           NaN    10708   Pave      IR1         Lvl    AllPub    Inside
167          86.0    10562   Pave      Reg         Lvl    AllPub    Inside
168          62.0     8244   Pave      IR1         Lvl    AllPub    Inside
170           NaN    12358   Pave      IR1         Lvl    AllPub    Inside
172          44.0     5306   Pave      IR1         Lvl    AllPub    Inside
173          80.0    10197   Pave      IR1         Lvl    AllPub    Inside
174          47.0    12416   Pave      IR1         Lvl    AllPub    Inside
177           NaN    13650   Pave      Reg         Lvl    AllPub    Inside
179          60.0     8520   Pave      Reg         Lvl    AllPub    Inside
180           NaN     2117   Pave      Reg         Lvl    AllPub    Inside
181          54.0     7588   Pave      Reg         Lvl    AllPub    Inside
182          60.0     9060   Pave      Reg         Lvl    AllPub    Inside
183          63.0    11426   Pave      Reg         Lvl    AllPub    Inside
184          92.0     7438   Pave      IR1         Lvl    AllPub    Inside
185          90.0    22950   Pave      IR2         Lvl    AllPub    Inside
187          60.0    10410   Pave      Reg         Lvl    AllPub    Inside
188          64.0     7018   Pave      Reg         Bnk    AllPub    Inside
189          41.0     4923   Pave      Reg         Lvl    AllPub    Inside
190          70.0    10570   Pave      Reg         Bnk    AllPub    Inside
192          68.0     9017   Pave      IR1         Lvl    AllPub    Inside
193          24.0     2522   Pave      Reg         Lvl    AllPub    Inside
194          60.0     7180   Pave      IR1         Lvl    AllPub    Inside
196          79.0     9416   Pave      Reg         Lvl    AllPub    Inside
199          76.0     9591   Pave      Reg         Lvl    AllPub    Inside
201          75.0    10125   Pave      Reg         Lvl    AllPub    Inside
203           NaN     4438   Pave      Reg         Lvl    AllPub    Inside
204          50.0     3500   Pave      Reg         Lvl    AllPub    Inside
207           NaN    12493   Pave      IR1         Lvl    AllPub    Inside
208           NaN    14364   Pave      IR1         Low    AllPub    Inside
209          75.0     8250   Pave      Reg         Lvl    AllPub    Inside
210          67.0     5604   Pave      Reg         Lvl    AllPub    Inside
212          72.0     8640   Pave      Reg         Lvl    AllPub    Inside
215          72.0    10011   Pave      IR1         Lvl    AllPub    Inside
216          65.0     8450   Pave      Reg         Lvl    AllPub    Inside
217          57.0     9906   Pave      Reg         Lvl    AllPub    Inside
219          43.0     3010   Pave      Reg         Lvl    AllPub    Inside
220          73.0     8990   Pave      IR1         Lvl    AllPub    Inside
221           NaN     8068   Pave      IR1         Lvl    AllPub    Inside
222          85.0    11475   Pave      Reg         Lvl    AllPub    Inside
224         103.0    13472   Pave      Reg         Lvl    AllPub    Inside
225          21.0     1680   Pave      Reg         Lvl    AllPub    Inside
226          82.0     9950   Pave      IR1         Lvl    AllPub    Inside
227          21.0     1869   Pave      Reg         Lvl    AllPub    Inside
229          43.0     3182   Pave      Reg         Lvl    AllPub    Inside
230          73.0     8760   Pave      Reg         Lvl    AllPub    Inside
231         174.0    15138   Pave      IR1         Lvl    AllPub    Inside
232          21.0     1680   Pave      Reg         Lvl    AllPub    Inside
234           NaN     7851   Pave      Reg         Lvl    AllPub    Inside
235          21.0     1680   Pave      Reg         Lvl    AllPub    Inside
238          93.0    12030   Pave      Reg         Lvl    AllPub    Inside
239          52.0     8741   Pave      Reg         Lvl    AllPub    Inside
240          75.0     9000   Pave      Reg         Lvl    AllPub    Inside
241          40.0     3880   Pave      Reg         Lvl    AllPub    Inside
244           NaN     8880   Pave      IR1         Lvl    AllPub    Inside
245          80.0    10400   Pave      Reg         Lvl    AllPub    Inside
246          69.0     9142   Pave      Reg         Lvl    AllPub    Inside
247          75.0    11310   Pave      Reg         Lvl    AllPub    Inside
248          72.0    11317   Pave      Reg         Lvl    AllPub    Inside
250          55.0     5350   Pave      IR1         Lvl    AllPub    Inside
251          44.0     4750   Pave      IR1         HLS    AllPub    Inside
252          65.0     8366   Pave      IR1         Lvl    AllPub    Inside
253          85.0     9350   Pave      Reg         Lvl    AllPub    Inside
254          70.0     8400   Pave      Reg         Lvl    AllPub    Inside
255          66.0     8738   Pave      IR1         Lvl    AllPub    Inside
256          64.0     8791   Pave      IR1         Lvl    AllPub    Inside
257          68.0     8814   Pave      Reg         Lvl    AllPub    Inside
258          80.0    12435   Pave      Reg         Lvl    AllPub    Inside
259          70.0    12702   Pave      Reg         Lvl    AllPub    Inside
261          69.0     9588   Pave      IR1         Lvl    AllPub    Inside
264          30.0     5232   Pave      IR3         Bnk    AllPub    Inside
265          78.0    12090   Pave      IR1         Lvl    AllPub    Inside
267          60.0     8400   Pave      Reg         Bnk    AllPub    Inside
268          71.0     6900   Pave      Reg         Lvl    AllPub    Inside
270          84.0    10728   Pave      Reg         Lvl    AllPub    Inside
273          80.0     9600   Pave      Reg         Lvl    AllPub    Inside
275          55.0     7264   Pave      Reg         Lvl    AllPub    Inside
276         129.0     9196   Pave      IR1         Lvl    AllPub    Inside
278         107.0    14450   Pave      Reg         Lvl    AllPub    Inside
279          83.0    10005   Pave      Reg         Lvl    AllPub    Inside
280          82.0    11287   Pave      Reg         Lvl    AllPub    Inside
281          60.0     7200   Pave      Reg         Lvl    AllPub    Inside
282          34.0     5063   Pave      Reg         Lvl    AllPub    Inside
283          74.0     9612   Pave      Reg         Lvl    AllPub    Inside
284          50.0     8012   Pave      Reg         Lvl    AllPub    Inside
285          35.0     4251   Pave      IR1         Lvl    AllPub    Inside
286          77.0     9786   Pave      IR1         Bnk    AllPub    Inside
288           NaN     9819   Pave      IR1         Lvl    AllPub    Inside
289          60.0     8730   Pave      Reg         Lvl    AllPub    Inside
290         120.0    15611   Pave      Reg         Lvl    AllPub    Inside
291          55.0     5687   Pave      Reg         Bnk    AllPub    Inside
292          60.0    11409   Pave      Reg         Lvl    AllPub    Inside
294          80.0     9600   Pave      Reg         Lvl    AllPub    Inside
296          75.0    13710   Pave      Reg         Lvl    AllPub    Inside
297          66.0     7399   Pave      IR1         Lvl    AllPub    Inside
298          90.0    11700   Pave      Reg         Lvl    AllPub    Inside
299          80.0    14000   Pave      Reg         Lvl    AllPub    Inside
301          66.0    16226   Pave      IR3         Lvl    AllPub    Inside
304          87.0    18386   Pave      Reg         Lvl    AllPub    Inside
305          80.0    10386   Pave      Reg         Lvl    AllPub    Inside
306         116.0    13474   Pave      Reg         Lvl    AllPub    Inside
307           NaN     7920   Pave      IR1         Lvl    AllPub    Inside
308           NaN    12342   Pave      IR1         Lvl    AllPub    Inside
309          90.0    12378   Pave      IR1         Lvl    AllPub    Inside
310           NaN     7685   Pave      IR1         Lvl    AllPub    Inside
311          50.0     8000   Pave      Reg         Lvl    AllPub    Inside
312          65.0     7800   Pave      Reg         Lvl    AllPub    Inside
313         150.0   215245   Pave      IR3         Low    AllPub    Inside
314          60.0     9600   Pave      Reg         Lvl    AllPub    Inside
315          71.0     7795   Pave      IR1         Lvl    AllPub    Inside
317          75.0     9000   Pave      Reg         Lvl    AllPub    Inside
318          90.0     9900   Pave      Reg         Low    AllPub    Inside
319           NaN    14115   Pave      Reg         Lvl    AllPub    Inside
321          99.0    12099   Pave      IR1         Lvl    AllPub    Inside
322          86.0    10380   Pave      IR1         Lvl    AllPub    Inside
323          49.0     5820   Pave      Reg         Lvl    AllPub    Inside
325          50.0     5000   Pave      Reg         Lvl    AllPub    Inside
327          80.0    11600   Pave      Reg         Lvl    AllPub    Inside
328           NaN    11888   Pave      IR1         Bnk    AllPub    Inside
330           NaN    10624   Pave      IR1         Lvl    AllPub    Inside
331          70.0     8176   Pave      Reg         Lvl    AllPub    Inside
332          85.0    10655   Pave      IR1         Lvl    AllPub    Inside
334          59.0     9042   Pave      IR1         Lvl    AllPub    Inside
337          70.0     9135   Pave      Reg         Lvl    AllPub    Inside
339          66.0    12400   Pave      IR1         Lvl    AllPub    Inside
340          85.0    14191   Pave      Reg         Lvl    AllPub    Inside
341          60.0     8400   Pave      Reg         Lvl    AllPub    Inside
342           NaN     8544   Pave      Reg         Lvl    AllPub    Inside
343          63.0     8849   Pave      IR1         Lvl    AllPub    Inside
344          36.0     2592   Pave      Reg         Lvl    AllPub    Inside
345          65.0     6435   Pave      Reg         Lvl    AllPub    Inside
347           NaN    17600   Pave      IR1         Lvl    AllPub    Inside
348          36.0     2448   Pave      Reg         Lvl    AllPub    Inside
349          56.0    20431   Pave      IR2         Lvl    AllPub    Inside
350          68.0     7820   Pave      IR1         Lvl    AllPub    Inside
351           NaN     5271   Pave      IR1         Low    AllPub    Inside
352          60.0     9084   Pave      Reg         Lvl    AllPub    Inside
353          60.0     8520   Pave      Reg         Lvl    AllPub    Inside
354          60.0     8400   Pave      Reg         Bnk    AllPub    Inside
355         105.0    11249   Pave      IR2         Lvl    AllPub    Inside
356           NaN     9248   Pave      IR1         Lvl    AllPub    Inside
357          44.0     4224   Pave      Reg         Lvl    AllPub    Inside
358          92.0     6930   Pave      IR1         Lvl    AllPub    Inside
361           NaN     9144   Pave      Reg         Lvl    AllPub    Inside
363          21.0     1680   Pave      Reg         Lvl    AllPub    Inside
365          59.0    10690   Pave      Reg         Lvl    AllPub    Inside
366           NaN     9500   Pave      IR1         Lvl    AllPub    Inside
368          78.0     7800   Pave      Reg         Lvl    AllPub    Inside
370           NaN     8121   Pave      IR1         Lvl    AllPub    Inside
371          80.0    17120   Pave      Reg         Lvl    AllPub    Inside
372          50.0     7175   Pave      Reg         Lvl    AllPub    Inside
373          79.0    10634   Pave      Reg         Lvl    AllPub    Inside
374          65.0     8200   Pave      Reg         Lvl    AllPub    Inside
375           NaN    10020   Pave      IR1         Low    AllPub    Inside
379          60.0     8123   Pave      IR1         Lvl    AllPub    Inside
380          50.0     5000   Pave      Reg         Lvl    AllPub    Inside
381          60.0     7200   Pave      Reg         Lvl    AllPub    Inside
382          79.0     9245   Pave      IR1         Lvl    AllPub    Inside
385          43.0     3182   Pave      Reg         Lvl    AllPub    Inside
387          72.0     7200   Pave      Reg         Lvl    AllPub    Inside
389          96.0    12474   Pave      Reg         Lvl    AllPub    Inside
390          50.0     8405   Pave      Reg         Lvl    AllPub    Inside
392           NaN     8339   Pave      IR1         Lvl    AllPub    Inside
394          60.0    10134   Pave      Reg         Lvl    AllPub    Inside

In [16]:
df_lot1 = df_drop_clm.loc[df_drop_clm["LotConfig"] == "Inside", "LotFrontage"]
df_lot1

0        65.0
2        68.0
5        85.0
6        75.0
8        51.0
10       70.0
11       85.0
12        NaN
13       91.0
17       72.0
18       66.0
19       70.0
21       57.0
22       75.0
23       44.0
24        NaN
27       98.0
29       60.0
30       50.0
33       70.0
34       60.0
35      108.0
37       74.0
38       68.0
39       65.0
40       84.0
41      115.0
44       70.0
45       61.0
47       84.0
48       33.0
49       66.0
51       52.0
53       68.0
54       60.0
55      100.0
56       24.0
59       60.0
60       63.0
61       60.0
62       44.0
63       50.0
64        NaN
65       76.0
66        NaN
67       72.0
70       95.0
73       85.0
75       21.0
76        NaN
77       50.0
78       72.0
82       78.0
83       80.0
84        NaN
86      122.0
89       60.0
90       60.0
91       85.0
92       80.0
94       69.0
96       78.0
97       73.0
99       77.0
100       NaN
101      77.0
102      64.0
105      75.0
106      60.0
107      50.0
109     105.0
110      75.0
111       NaN
112      77.0
114      61.0
116       NaN
119      65.0
121      50.0
123      55.0
125      60.0
126       NaN
127      55.0
128      69.0
129      69.0
133       NaN
134      78.0
135      80.0
137      82.0
138      73.0
139      65.0
141      78.0
143      78.0
144      70.0
145      24.0
148      63.0
149       NaN
151     107.0
153       NaN
156      60.0
161     110.0
163      55.0
165      62.0
166       NaN
167      86.0
168      62.0
170       NaN
172      44.0
173      80.0
174      47.0
177       NaN
179      60.0
180       NaN
181      54.0
182      60.0
183      63.0
184      92.0
185      90.0
187      60.0
188      64.0
189      41.0
190      70.0
192      68.0
193      24.0
194      60.0
196      79.0
199      76.0
201      75.0
203       NaN
204      50.0
207       NaN
208       NaN
209      75.0
210      67.0
212      72.0
215      72.0
216      65.0
217      57.0
219      43.0
220      73.0
221       NaN
222      85.0
224     103.0
225      21.0
226      82.0
227      21.0
229      43.0
230      73.0
231     174.0
232      21.0
234       NaN
235      21.0
238      93.0
239      52.0
240      75.0
241      40.0
244       NaN
245      80.0
246      69.0
247      75.0
248      72.0
250      55.0
251      44.0
252      65.0
253      85.0
254      70.0
255      66.0
256      64.0
257      68.0
258      80.0
259      70.0
261      69.0
264      30.0
265      78.0
267      60.0
268      71.0
270      84.0
273      80.0
275      55.0
276     129.0
278     107.0
279      83.0
280      82.0
281      60.0
282      34.0
283      74.0
284      50.0
285      35.0
286      77.0
288       NaN
289      60.0
290     120.0
291      55.0
292      60.0
294      80.0
296      75.0
297      66.0
298      90.0
299      80.0
301      66.0
304      87.0
305      80.0
306     116.0
307       NaN
308       NaN
309      90.0
310       NaN
311      50.0
312      65.0
313     150.0
314      60.0
315      71.0
317      75.0
318      90.0
319       NaN
321      99.0
322      86.0
323      49.0
325      50.0
327      80.0
328       NaN
330       NaN
331      70.0
332      85.0
334      59.0
337      70.0
339      66.0
340      85.0
341      60.0
342       NaN
343      63.0
344      36.0
345      65.0
347       NaN
348      36.0
349      56.0
350      68.0
351       NaN
352      60.0
353      60.0
354      60.0
355     105.0
356       NaN
357      44.0
358      92.0
361       NaN
363      21.0
365      59.0
366       NaN
368      78.0
370       NaN
371      80.0
372      50.0
373      79.0
374      65.0
375       NaN
379      60.0
380      50.0
381      60.0
382      79.0
385      43.0
387      72.0
389      96.0
390      50.0
392       NaN
394      60.0
395      68.0
396      60.0
397      69.0
399      65.0
400      38.0
401      65.0
402      60.0
404       NaN
406      51.0
407      63.0
409      85.0
410      68.0
411     100.0
412       NaN
413      56.0
415      73.0
416      74.0
417      86.0
418      60.0
419      65.0
420      78.0
422     100.0
423      80.0
424      72.0
425      60.0
426       NaN
427      77.0
428      64.0
430      21.0
431      60.0
432      24.0
434      21.0
436      40.0
437      50.0
438      40.0
440     105.0
441      92.0
442      52.0
443      53.0
444      70.0
448      50.0
449      50.0
450      70.0
451      62.0
453      75.0
454      63.0
455      80.0
456      34.0
458       NaN
460      75.0
461      60.0
462      60.0
463      74.0
464      60.0
465       NaN
466      85.0
467      79.0
468      98.0
471      92.0
472      35.0
473     110.0
474      41.0
476      75.0
477     105.0
478      79.0
479      50.0
481      72.0
485      80.0
486      79.0
487      70.0
489      21.0
490       NaN
491      79.0
493      70.0
494      50.0
495      60.0
496       NaN
497      60.0
498      65.0
499      70.0
500      21.0
501      75.0
503     100.0
504      24.0
505      60.0
506      80.0
507      75.0
508      60.0
510      75.0
511      40.0
514      55.0
515      94.0
517      79.0
519      53.0
520      60.0
523     130.0
524      95.0
525      62.0
526      70.0
527      67.0
528      58.0
530      85.0
532      60.0
533      50.0
534      74.0
535      70.0
538       NaN
539       NaN
540      85.0
542      78.0
543      34.0
544      58.0
546      70.0
547      54.0
548      49.0
549      75.0
550      53.0
551      50.0
552      87.0
553      67.0
554      85.0
555      58.0
556      69.0
557      60.0
559       NaN
560       NaN
561      77.0
562      63.0
563      66.0
566      77.0
567      70.0
568      79.0
570      74.0
571      60.0
573      76.0
575      80.0
576      52.0
577      96.0
579      81.0
581      98.0
582      81.0
583      75.0
584      51.0
585      88.0
586      55.0
587      74.0
588      65.0
589      50.0
590      64.0
592      60.0
593       NaN
594      88.0
595      69.0
596      60.0
597      53.0
598      80.0
599      24.0
600      74.0
601      50.0
602      80.0
603      30.0
604      88.0
605      85.0
607      78.0
608      78.0
609      61.0
610       NaN
612       NaN
613      70.0
614      21.0
615      80.0
616       NaN
618      90.0
619      85.0
620      45.0
621      90.0
622      71.0
623       NaN
624      80.0
626       NaN
627      80.0
628      70.0
631      34.0
632      85.0
634      64.0
635      60.0
636      51.0
637      50.0
638      67.0
639      53.0
640      62.0
641       NaN
642      75.0
643      80.0
644      85.0
646      60.0
647      85.0
648      70.0
649      21.0
650      65.0
651      60.0
652      70.0
653      60.0
654      91.0
655      21.0
656      72.0
657      60.0
658      78.0
663      90.0
666       NaN
667      65.0
669      80.0
671      54.0
672       NaN
673     110.0
674      80.0
675      24.0
676      60.0
677      52.0
678      80.0
679       NaN
680      50.0
681      55.0
682       NaN
686      84.0
688      60.0
690       NaN
692      42.0
695      54.0
696      50.0
697      57.0
698      65.0
699      59.0
700      85.0
701      80.0
702      82.0
703      76.0
704      70.0
705      70.0
707      48.0
708      65.0
709       NaN
710      56.0
711      66.0
712      40.0
713      60.0
715      78.0
716      60.0
717      80.0
718      96.0
719      69.0
721       NaN
722      70.0
723      60.0
724      86.0
725      60.0
727      64.0
729      52.0
730      39.0
732      75.0
735      60.0
736      60.0
738      60.0
739      65.0
740      60.0
741      65.0
742      65.0
743      70.0
744      41.0
745       NaN
746       NaN
748      59.0
749      50.0
751       NaN
752      79.0
753      80.0
754      61.0
755      34.0
756      68.0
758      24.0
759      65.0
760      70.0
762      72.0
763      82.0
765      75.0
766      80.0
767      75.0
768      70.0
771      67.0
772      94.0
773      70.0
776      86.0
777     100.0
778      60.0
779      78.0
780      63.0
781      65.0
782      67.0
784      35.0
785       NaN
786      60.0
787      76.0
789       NaN
790      43.0
793      76.0
795      70.0
796      71.0
797      57.0
798     104.0
800      79.0
801      40.0
802      63.0
803     107.0
804      75.0
806      75.0
807     144.0
808      85.0
810      78.0
811       NaN
812      66.0
813      75.0
814      45.0
818      80.0
819      44.0
821      60.0
823      60.0
824      81.0
825     114.0
826      50.0
827      65.0
829      24.0
831      30.0
833     100.0
834      75.0
835      60.0
836      90.0
837      21.0
838      75.0
839      70.0
840       NaN
841      60.0
842      82.0
844     100.0
846      75.0
848      75.0
850      36.0
851       NaN
852      53.0
854     102.0
856       NaN
857      65.0
858      80.0
861      75.0
863      70.0
864      72.0
865       NaN
866      67.0
869      80.0
870      60.0
871      70.0
873      60.0
874      52.0
875      75.0
876      94.0
877      74.0
878      88.0
880      60.0
883      60.0
884      65.0
887      59.0
888      95.0
889     128.0
891      70.0
892      70.0
893       NaN
894      64.0
895      71.0
896      50.0
897      64.0
898     100.0
899      65.0
900       NaN
901      64.0
902      63.0
904       NaN
905      80.0
907      86.0
908       NaN
909     149.0
912      51.0
913      82.0
914      30.0
915      21.0
916      50.0
917       NaN
920      70.0
921      67.0
922      65.0
923      50.0
924      79.0
926      93.0
927       NaN
928       NaN
930      73.0
931      70.0
934     313.0
935      52.0
936      67.0
937      75.0
938      73.0
939       NaN
940      55.0
942      42.0
943     100.0
946      70.0
947      85.0
948      65.0
949      78.0
950      60.0
952      60.0
953       NaN
955      82.0
956      24.0
957      70.0
958      65.0
960      50.0
965      65.0
966     130.0
967       NaN
968      50.0
969      75.0
970      60.0
971      36.0
972      55.0
976      51.0
977      35.0
978      68.0
982      43.0
984      75.0
985      68.0
987      83.0
988       NaN
989      65.0
990      82.0
992      80.0
993      68.0
995      51.0
996       NaN
997       NaN
998      60.0
999      64.0
1002     75.0
1004     43.0
1005     65.0
1006      NaN
1007     21.0
1009     60.0
1010    115.0
1011     75.0
1012     55.0
1013     60.0
1014     60.0
1015     70.0
1016     73.0
1019     43.0
1020     60.0
1021     64.0
1022     52.0
1023     43.0
1026     73.0
1027     71.0
1028     79.0
1029     21.0
1030      NaN
1033      NaN
1034     50.0
1036     89.0
1037      NaN
1038     21.0
1039     21.0
1041      NaN
1042     34.0
1043     86.0
1044     80.0
1046     85.0
1047     57.0
1048    100.0
1049     60.0
1050     73.0
1053     68.0
1055    104.0
1056     43.0
1058     96.0
1060     41.0
1061    120.0
1062     85.0
1063     50.0
1065     80.0
1066     59.0
1067     80.0
1068     42.0
1069     60.0
1070     72.0
1071     78.0
1072     50.0
1074     74.0
1075     75.0
1076     60.0
1078     37.0
1079     65.0
1080     80.0
1082     70.0
1083     80.0
1085     73.0
1086      NaN
1087     85.0
1088     24.0
1089     37.0
1091     24.0
1092     60.0
1094     74.0
1095     78.0
1096     60.0
1097      NaN
1098     50.0
1099     82.0
1100     60.0
1101     61.0
1102     70.0
1104     24.0
1108      NaN
1109    107.0
1110      NaN
1111     80.0
1113     66.0
1114     90.0
1115     93.0
1116      NaN
1118     85.0
1119     70.0
1120     59.0
1121     84.0
1123     50.0
1124      NaN
1125     60.0
1126     53.0
1128     59.0
1129     60.0
1130     65.0
1131     63.0
1132     90.0
1133     80.0
1134     57.0
1136     80.0
1137     54.0
1138      NaN
1139     98.0
1142     77.0
1143      NaN
1144     60.0
1145     52.0
1146      NaN
1147     75.0
1148      NaN
1149     50.0
1150     57.0
1151    134.0
1152     90.0
1154      NaN
1156     85.0
1157     34.0
1159     76.0
1160     24.0
1162    109.0
1163     60.0
1165     79.0
1167     58.0
1170     76.0
1171     76.0
1172     35.0
1173    138.0
1174     80.0
1175     85.0
1177      NaN
1181     64.0
1183     60.0
1184     50.0
1185     60.0
1188     68.0
1189     60.0
1190      NaN
1191     24.0
1192     60.0
1195     51.0
1196     58.0
1198     70.0
1199     75.0
1200     71.0
1203     75.0
1204     78.0
1206      NaN
1207     70.0
1208     70.0
1210     70.0
1211    152.0
1212     50.0
1214     69.0
1215     99.0
1216     68.0
1217     72.0
1218     52.0
1219     21.0
1220     66.0
1221     55.0
1222     78.0
1223     89.0
1224     60.0
1225     65.0
1229     70.0
1230      NaN
1231     70.0
1233      NaN
1234     55.0
1235     96.0
1236     36.0
1238     63.0
1239     64.0
1240     65.0
1241     83.0
1242     85.0
1243    107.0
1245     78.0
1246     65.0
1247      NaN
1248     60.0
1249     60.0
1252     62.0
1253      NaN
1254     60.0
1255     52.0
1258     59.0
1261     80.0
1262      NaN
1263     60.0
1264     34.0
1266     60.0
1267     89.0
1268      NaN
1269     78.0
1270      NaN
1271      NaN
1278     75.0
1279     60.0
1280     67.0
1282     61.0
1284     50.0
1285     50.0
1286      NaN
1287      NaN
1288     40.0
1289     86.0
1291     21.0
1293     78.0
1294     60.0
1295     70.0
1296     80.0
1297     35.0
1299     75.0
1301      NaN
1302     92.0
1303     73.0
1304     32.0
1306     48.0
1307     60.0
1308    100.0
1309      NaN
1310    100.0
1311     68.0
1312      NaN
1314     60.0
1315     85.0
1316     61.0
1319     75.0
1320     70.0
1322    107.0
1323     50.0
1324     75.0
1325     40.0
1326     70.0
1327     60.0
1329     63.0
1330     85.0
1331     55.0
1332     67.0
1334     24.0
1335     80.0
1336     87.0
1340     70.0
1341     66.0
1342      NaN
1343     57.0
1345     50.0
1348      NaN
1349     50.0
1350     91.0
1351     70.0
1352     50.0
1354      NaN
1355    102.0
1358      NaN
1360     51.0
1361    124.0
1363     73.0
1364     30.0
1365      NaN
1366     68.0
1367     41.0
1368      NaN
1371     80.0
1373      NaN
1374     85.0
1375     89.0
1376     52.0
1377     60.0
1378     21.0
1379     73.0
1380     45.0
1383      NaN
1384     60.0
1385     40.0
1386     80.0
1387     60.0
1389     60.0
1390     70.0
1391     65.0
1392     68.0
1393     60.0
1394     53.0
1395     88.0
1396      NaN
1397     51.0
1398     60.0
1399     51.0
1401     62.0
1402     64.0
1405     44.0
1408     60.0
1410     79.0
1411     80.0
1412     60.0
1414     64.0
1415     51.0
1416     60.0
1417      NaN
1418     71.0
1419      NaN
1421     53.0
1422     37.0
1424      NaN
1425     80.0
1426     81.0
1427     60.0
1430     60.0
1431      NaN
1432     60.0
1433     93.0
1434     80.0
1435     80.0
1438     90.0
1439     80.0
1440     79.0
1441      NaN
1442     85.0
1443      NaN
1445     70.0
1447     80.0
1448     70.0
1449     21.0
1451     78.0
1452     35.0
1453     90.0
1454     62.0
1455     62.0
1456     85.0
1457     66.0
1458     68.0
1459     75.0
Name: LotFrontage, dtype: float64

In [17]:
df_lot1 = df_lot1.replace(np.nan, df_lot1.mean())
df_lot1

0        65.000000
2        68.000000
5        85.000000
6        75.000000
8        51.000000
10       70.000000
11       85.000000
12       67.715686
13       91.000000
17       72.000000
18       66.000000
19       70.000000
21       57.000000
22       75.000000
23       44.000000
24       67.715686
27       98.000000
29       60.000000
30       50.000000
33       70.000000
34       60.000000
35      108.000000
37       74.000000
38       68.000000
39       65.000000
40       84.000000
41      115.000000
44       70.000000
45       61.000000
47       84.000000
48       33.000000
49       66.000000
51       52.000000
53       68.000000
54       60.000000
55      100.000000
56       24.000000
59       60.000000
60       63.000000
61       60.000000
62       44.000000
63       50.000000
64       67.715686
65       76.000000
66       67.715686
67       72.000000
70       95.000000
73       85.000000
75       21.000000
76       67.715686
77       50.000000
78       72.000000
82       78.000000
83       80.000000
84       67.715686
86      122.000000
89       60.000000
90       60.000000
91       85.000000
92       80.000000
94       69.000000
96       78.000000
97       73.000000
99       77.000000
100      67.715686
101      77.000000
102      64.000000
105      75.000000
106      60.000000
107      50.000000
109     105.000000
110      75.000000
111      67.715686
112      77.000000
114      61.000000
116      67.715686
119      65.000000
121      50.000000
123      55.000000
125      60.000000
126      67.715686
127      55.000000
128      69.000000
129      69.000000
133      67.715686
134      78.000000
135      80.000000
137      82.000000
138      73.000000
139      65.000000
141      78.000000
143      78.000000
144      70.000000
145      24.000000
148      63.000000
149      67.715686
151     107.000000
153      67.715686
156      60.000000
161     110.000000
163      55.000000
165      62.000000
166      67.715686
167      86.000000
168      62.000000
170      67.715686
172      44.000000
173      80.000000
174      47.000000
177      67.715686
179      60.000000
180      67.715686
181      54.000000
182      60.000000
183      63.000000
184      92.000000
185      90.000000
187      60.000000
188      64.000000
189      41.000000
190      70.000000
192      68.000000
193      24.000000
194      60.000000
196      79.000000
199      76.000000
201      75.000000
203      67.715686
204      50.000000
207      67.715686
208      67.715686
209      75.000000
210      67.000000
212      72.000000
215      72.000000
216      65.000000
217      57.000000
219      43.000000
220      73.000000
221      67.715686
222      85.000000
224     103.000000
225      21.000000
226      82.000000
227      21.000000
229      43.000000
230      73.000000
231     174.000000
232      21.000000
234      67.715686
235      21.000000
238      93.000000
239      52.000000
240      75.000000
241      40.000000
244      67.715686
245      80.000000
246      69.000000
247      75.000000
248      72.000000
250      55.000000
251      44.000000
252      65.000000
253      85.000000
254      70.000000
255      66.000000
256      64.000000
257      68.000000
258      80.000000
259      70.000000
261      69.000000
264      30.000000
265      78.000000
267      60.000000
268      71.000000
270      84.000000
273      80.000000
275      55.000000
276     129.000000
278     107.000000
279      83.000000
280      82.000000
281      60.000000
282      34.000000
283      74.000000
284      50.000000
285      35.000000
286      77.000000
288      67.715686
289      60.000000
290     120.000000
291      55.000000
292      60.000000
294      80.000000
296      75.000000
297      66.000000
298      90.000000
299      80.000000
301      66.000000
304      87.000000
305      80.000000
306     116.000000
307      67.715686
308      67.715686
309      90.000000
310      67.715686
311      50.000000
312      65.000000
313     150.000000
314      60.000000
315      71.000000
317      75.000000
318      90.000000
319      67.715686
321      99.000000
322      86.000000
323      49.000000
325      50.000000
327      80.000000
328      67.715686
330      67.715686
331      70.000000
332      85.000000
334      59.000000
337      70.000000
339      66.000000
340      85.000000
341      60.000000
342      67.715686
343      63.000000
344      36.000000
345      65.000000
347      67.715686
348      36.000000
349      56.000000
350      68.000000
351      67.715686
352      60.000000
353      60.000000
354      60.000000
355     105.000000
356      67.715686
357      44.000000
358      92.000000
361      67.715686
363      21.000000
365      59.000000
366      67.715686
368      78.000000
370      67.715686
371      80.000000
372      50.000000
373      79.000000
374      65.000000
375      67.715686
379      60.000000
380      50.000000
381      60.000000
382      79.000000
385      43.000000
387      72.000000
389      96.000000
390      50.000000
392      67.715686
394      60.000000
395      68.000000
396      60.000000
397      69.000000
399      65.000000
400      38.000000
401      65.000000
402      60.000000
404      67.715686
406      51.000000
407      63.000000
409      85.000000
410      68.000000
411     100.000000
412      67.715686
413      56.000000
415      73.000000
416      74.000000
417      86.000000
418      60.000000
419      65.000000
420      78.000000
422     100.000000
423      80.000000
424      72.000000
425      60.000000
426      67.715686
427      77.000000
428      64.000000
430      21.000000
431      60.000000
432      24.000000
434      21.000000
436      40.000000
437      50.000000
438      40.000000
440     105.000000
441      92.000000
442      52.000000
443      53.000000
444      70.000000
448      50.000000
449      50.000000
450      70.000000
451      62.000000
453      75.000000
454      63.000000
455      80.000000
456      34.000000
458      67.715686
460      75.000000
461      60.000000
462      60.000000
463      74.000000
464      60.000000
465      67.715686
466      85.000000
467      79.000000
468      98.000000
471      92.000000
472      35.000000
473     110.000000
474      41.000000
476      75.000000
477     105.000000
478      79.000000
479      50.000000
481      72.000000
485      80.000000
486      79.000000
487      70.000000
489      21.000000
490      67.715686
491      79.000000
493      70.000000
494      50.000000
495      60.000000
496      67.715686
497      60.000000
498      65.000000
499      70.000000
500      21.000000
501      75.000000
503     100.000000
504      24.000000
505      60.000000
506      80.000000
507      75.000000
508      60.000000
510      75.000000
511      40.000000
514      55.000000
515      94.000000
517      79.000000
519      53.000000
520      60.000000
523     130.000000
524      95.000000
525      62.000000
526      70.000000
527      67.000000
528      58.000000
530      85.000000
532      60.000000
533      50.000000
534      74.000000
535      70.000000
538      67.715686
539      67.715686
540      85.000000
542      78.000000
543      34.000000
544      58.000000
546      70.000000
547      54.000000
548      49.000000
549      75.000000
550      53.000000
551      50.000000
552      87.000000
553      67.000000
554      85.000000
555      58.000000
556      69.000000
557      60.000000
559      67.715686
560      67.715686
561      77.000000
562      63.000000
563      66.000000
566      77.000000
567      70.000000
568      79.000000
570      74.000000
571      60.000000
573      76.000000
575      80.000000
576      52.000000
577      96.000000
579      81.000000
581      98.000000
582      81.000000
583      75.000000
584      51.000000
585      88.000000
586      55.000000
587      74.000000
588      65.000000
589      50.000000
590      64.000000
592      60.000000
593      67.715686
594      88.000000
595      69.000000
596      60.000000
597      53.000000
598      80.000000
599      24.000000
600      74.000000
601      50.000000
602      80.000000
603      30.000000
604      88.000000
605      85.000000
607      78.000000
608      78.000000
609      61.000000
610      67.715686
612      67.715686
613      70.000000
614      21.000000
615      80.000000
616      67.715686
618      90.000000
619      85.000000
620      45.000000
621      90.000000
622      71.000000
623      67.715686
624      80.000000
626      67.715686
627      80.000000
628      70.000000
631      34.000000
632      85.000000
634      64.000000
635      60.000000
636      51.000000
637      50.000000
638      67.000000
639      53.000000
640      62.000000
641      67.715686
642      75.000000
643      80.000000
644      85.000000
646      60.000000
647      85.000000
648      70.000000
649      21.000000
650      65.000000
651      60.000000
652      70.000000
653      60.000000
654      91.000000
655      21.000000
656      72.000000
657      60.000000
658      78.000000
663      90.000000
666      67.715686
667      65.000000
669      80.000000
671      54.000000
672      67.715686
673     110.000000
674      80.000000
675      24.000000
676      60.000000
677      52.000000
678      80.000000
679      67.715686
680      50.000000
681      55.000000
682      67.715686
686      84.000000
688      60.000000
690      67.715686
692      42.000000
695      54.000000
696      50.000000
697      57.000000
698      65.000000
699      59.000000
700      85.000000
701      80.000000
702      82.000000
703      76.000000
704      70.000000
705      70.000000
707      48.000000
708      65.000000
709      67.715686
710      56.000000
711      66.000000
712      40.000000
713      60.000000
715      78.000000
716      60.000000
717      80.000000
718      96.000000
719      69.000000
721      67.715686
722      70.000000
723      60.000000
724      86.000000
725      60.000000
727      64.000000
729      52.000000
730      39.000000
732      75.000000
735      60.000000
736      60.000000
738      60.000000
739      65.000000
740      60.000000
741      65.000000
742      65.000000
743      70.000000
744      41.000000
745      67.715686
746      67.715686
748      59.000000
749      50.000000
751      67.715686
752      79.000000
753      80.000000
754      61.000000
755      34.000000
756      68.000000
758      24.000000
759      65.000000
760      70.000000
762      72.000000
763      82.000000
765      75.000000
766      80.000000
767      75.000000
768      70.000000
771      67.000000
772      94.000000
773      70.000000
776      86.000000
777     100.000000
778      60.000000
779      78.000000
780      63.000000
781      65.000000
782      67.000000
784      35.000000
785      67.715686
786      60.000000
787      76.000000
789      67.715686
790      43.000000
793      76.000000
795      70.000000
796      71.000000
797      57.000000
798     104.000000
800      79.000000
801      40.000000
802      63.000000
803     107.000000
804      75.000000
806      75.000000
807     144.000000
808      85.000000
810      78.000000
811      67.715686
812      66.000000
813      75.000000
814      45.000000
818      80.000000
819      44.000000
821      60.000000
823      60.000000
824      81.000000
825     114.000000
826      50.000000
827      65.000000
829      24.000000
831      30.000000
833     100.000000
834      75.000000
835      60.000000
836      90.000000
837      21.000000
838      75.000000
839      70.000000
840      67.715686
841      60.000000
842      82.000000
844     100.000000
846      75.000000
848      75.000000
850      36.000000
851      67.715686
852      53.000000
854     102.000000
856      67.715686
857      65.000000
858      80.000000
861      75.000000
863      70.000000
864      72.000000
865      67.715686
866      67.000000
869      80.000000
870      60.000000
871      70.000000
873      60.000000
874      52.000000
875      75.000000
876      94.000000
877      74.000000
878      88.000000
880      60.000000
883      60.000000
884      65.000000
887      59.000000
888      95.000000
889     128.000000
891      70.000000
892      70.000000
893      67.715686
894      64.000000
895      71.000000
896      50.000000
897      64.000000
898     100.000000
899      65.000000
900      67.715686
901      64.000000
902      63.000000
904      67.715686
905      80.000000
907      86.000000
908      67.715686
909     149.000000
912      51.000000
913      82.000000
914      30.000000
915      21.000000
916      50.000000
917      67.715686
920      70.000000
921      67.000000
922      65.000000
923      50.000000
924      79.000000
926      93.000000
927      67.715686
928      67.715686
930      73.000000
931      70.000000
934     313.000000
935      52.000000
936      67.000000
937      75.000000
938      73.000000
939      67.715686
940      55.000000
942      42.000000
943     100.000000
946      70.000000
947      85.000000
948      65.000000
949      78.000000
950      60.000000
952      60.000000
953      67.715686
955      82.000000
956      24.000000
957      70.000000
958      65.000000
960      50.000000
965      65.000000
966     130.000000
967      67.715686
968      50.000000
969      75.000000
970      60.000000
971      36.000000
972      55.000000
976      51.000000
977      35.000000
978      68.000000
982      43.000000
984      75.000000
985      68.000000
987      83.000000
988      67.715686
989      65.000000
990      82.000000
992      80.000000
993      68.000000
995      51.000000
996      67.715686
997      67.715686
998      60.000000
999      64.000000
1002     75.000000
1004     43.000000
1005     65.000000
1006     67.715686
1007     21.000000
1009     60.000000
1010    115.000000
1011     75.000000
1012     55.000000
1013     60.000000
1014     60.000000
1015     70.000000
1016     73.000000
1019     43.000000
1020     60.000000
1021     64.000000
1022     52.000000
1023     43.000000
1026     73.000000
1027     71.000000
1028     79.000000
1029     21.000000
1030     67.715686
1033     67.715686
1034     50.000000
1036     89.000000
1037     67.715686
1038     21.000000
1039     21.000000
1041     67.715686
1042     34.000000
1043     86.000000
1044     80.000000
1046     85.000000
1047     57.000000
1048    100.000000
1049     60.000000
1050     73.000000
1053     68.000000
1055    104.000000
1056     43.000000
1058     96.000000
1060     41.000000
1061    120.000000
1062     85.000000
1063     50.000000
1065     80.000000
1066     59.000000
1067     80.000000
1068     42.000000
1069     60.000000
1070     72.000000
1071     78.000000
1072     50.000000
1074     74.000000
1075     75.000000
1076     60.000000
1078     37.000000
1079     65.000000
1080     80.000000
1082     70.000000
1083     80.000000
1085     73.000000
1086     67.715686
1087     85.000000
1088     24.000000
1089     37.000000
1091     24.000000
1092     60.000000
1094     74.000000
1095     78.000000
1096     60.000000
1097     67.715686
1098     50.000000
1099     82.000000
1100     60.000000
1101     61.000000
1102     70.000000
1104     24.000000
1108     67.715686
1109    107.000000
1110     67.715686
1111     80.000000
1113     66.000000
1114     90.000000
1115     93.000000
1116     67.715686
1118     85.000000
1119     70.000000
1120     59.000000
1121     84.000000
1123     50.000000
1124     67.715686
1125     60.000000
1126     53.000000
1128     59.000000
1129     60.000000
1130     65.000000
1131     63.000000
1132     90.000000
1133     80.000000
1134     57.000000
1136     80.000000
1137     54.000000
1138     67.715686
1139     98.000000
1142     77.000000
1143     67.715686
1144     60.000000
1145     52.000000
1146     67.715686
1147     75.000000
1148     67.715686
1149     50.000000
1150     57.000000
1151    134.000000
1152     90.000000
1154     67.715686
1156     85.000000
1157     34.000000
1159     76.000000
1160     24.000000
1162    109.000000
1163     60.000000
1165     79.000000
1167     58.000000
1170     76.000000
1171     76.000000
1172     35.000000
1173    138.000000
1174     80.000000
1175     85.000000
1177     67.715686
1181     64.000000
1183     60.000000
1184     50.000000
1185     60.000000
1188     68.000000
1189     60.000000
1190     67.715686
1191     24.000000
1192     60.000000
1195     51.000000
1196     58.000000
1198     70.000000
1199     75.000000
1200     71.000000
1203     75.000000
1204     78.000000
1206     67.715686
1207     70.000000
1208     70.000000
1210     70.000000
1211    152.000000
1212     50.000000
1214     69.000000
1215     99.000000
1216     68.000000
1217     72.000000
1218     52.000000
1219     21.000000
1220     66.000000
1221     55.000000
1222     78.000000
1223     89.000000
1224     60.000000
1225     65.000000
1229     70.000000
1230     67.715686
1231     70.000000
1233     67.715686
1234     55.000000
1235     96.000000
1236     36.000000
1238     63.000000
1239     64.000000
1240     65.000000
1241     83.000000
1242     85.000000
1243    107.000000
1245     78.000000
1246     65.000000
1247     67.715686
1248     60.000000
1249     60.000000
1252     62.000000
1253     67.715686
1254     60.000000
1255     52.000000
1258     59.000000
1261     80.000000
1262     67.715686
1263     60.000000
1264     34.000000
1266     60.000000
1267     89.000000
1268     67.715686
1269     78.000000
1270     67.715686
1271     67.715686
1278     75.000000
1279     60.000000
1280     67.000000
1282     61.000000
1284     50.000000
1285     50.000000
1286     67.715686
1287     67.715686
1288     40.000000
1289     86.000000
1291     21.000000
1293     78.000000
1294     60.000000
1295     70.000000
1296     80.000000
1297     35.000000
1299     75.000000
1301     67.715686
1302     92.000000
1303     73.000000
1304     32.000000
1306     48.000000
1307     60.000000
1308    100.000000
1309     67.715686
1310    100.000000
1311     68.000000
1312     67.715686
1314     60.000000
1315     85.000000
1316     61.000000
1319     75.000000
1320     70.000000
1322    107.000000
1323     50.000000
1324     75.000000
1325     40.000000
1326     70.000000
1327     60.000000
1329     63.000000
1330     85.000000
1331     55.000000
1332     67.000000
1334     24.000000
1335     80.000000
1336     87.000000
1340     70.000000
1341     66.000000
1342     67.715686
1343     57.000000
1345     50.000000
1348     67.715686
1349     50.000000
1350     91.000000
1351     70.000000
1352     50.000000
1354     67.715686
1355    102.000000
1358     67.715686
1360     51.000000
1361    124.000000
1363     73.000000
1364     30.000000
1365     67.715686
1366     68.000000
1367     41.000000
1368     67.715686
1371     80.000000
1373     67.715686
1374     85.000000
1375     89.000000
1376     52.000000
1377     60.000000
1378     21.000000
1379     73.000000
1380     45.000000
1383     67.715686
1384     60.000000
1385     40.000000
1386     80.000000
1387     60.000000
1389     60.000000
1390     70.000000
1391     65.000000
1392     68.000000
1393     60.000000
1394     53.000000
1395     88.000000
1396     67.715686
1397     51.000000
1398     60.000000
1399     51.000000
1401     62.000000
1402     64.000000
1405     44.000000
1408     60.000000
1410     79.000000
1411     80.000000
1412     60.000000
1414     64.000000
1415     51.000000
1416     60.000000
1417     67.715686
1418     71.000000
1419     67.715686
1421     53.000000
1422     37.000000
1424     67.715686
1425     80.000000
1426     81.000000
1427     60.000000
1430     60.000000
1431     67.715686
1432     60.000000
1433     93.000000
1434     80.000000
1435     80.000000
1438     90.000000
1439     80.000000
1440     79.000000
1441     67.715686
1442     85.000000
1443     67.715686
1445     70.000000
1447     80.000000
1448     70.000000
1449     21.000000
1451     78.000000
1452     35.000000
1453     90.000000
1454     62.000000
1455     62.000000
1456     85.000000
1457     66.000000
1458     68.000000
1459     75.000000

In [18]:
for i in l2:
    df_drop_clm.loc[df_drop_clm["LotConfig"] == i, "LotFrontage"] = df_drop_clm.loc[df_drop_clm["LotConfig"] == i, "LotFrontage"].replace(np.nan, df_drop_clm.loc[df_drop_clm["LotConfig"] == i, "LotFrontage"].mean())

In [19]:
df_drop_clm["LotFrontage"]

0        65.000000
1        80.000000
2        68.000000
3        60.000000
4        84.000000
5        85.000000
6        75.000000
7        84.039801
8        51.000000
9        50.000000
10       70.000000
11       85.000000
12       67.715686
13       91.000000
14       84.039801
15       51.000000
16       59.911111
17       72.000000
18       66.000000
19       70.000000
20      101.000000
21       57.000000
22       75.000000
23       44.000000
24       67.715686
25      110.000000
26       60.000000
27       98.000000
28       47.000000
29       60.000000
30       50.000000
31       59.911111
32       85.000000
33       70.000000
34       60.000000
35      108.000000
36      112.000000
37       74.000000
38       68.000000
39       65.000000
40       84.000000
41      115.000000
42       59.911111
43       59.911111
44       70.000000
45       61.000000
46       48.000000
47       84.000000
48       33.000000
49       66.000000
50       84.039801
51       52.000000
52      110.000000
53       68.000000
54       60.000000
55      100.000000
56       24.000000
57       89.000000
58       66.000000
59       60.000000
60       63.000000
61       60.000000
62       44.000000
63       50.000000
64       67.715686
65       76.000000
66       67.715686
67       72.000000
68       47.000000
69       81.000000
70       95.000000
71       69.000000
72       74.000000
73       85.000000
74       60.000000
75       21.000000
76       67.715686
77       50.000000
78       72.000000
79       60.000000
80      100.000000
81       32.000000
82       78.000000
83       80.000000
84       67.715686
85      121.000000
86      122.000000
87       40.000000
88      105.000000
89       60.000000
90       60.000000
91       85.000000
92       80.000000
93       60.000000
94       69.000000
95       84.039801
96       78.000000
97       73.000000
98       85.000000
99       77.000000
100      67.715686
101      77.000000
102      64.000000
103      94.000000
104      84.039801
105      75.000000
106      60.000000
107      50.000000
108      85.000000
109     105.000000
110      75.000000
111      67.715686
112      77.000000
113      84.039801
114      61.000000
115      34.000000
116      67.715686
117      74.000000
118      90.000000
119      65.000000
120      59.911111
121      50.000000
122      75.000000
123      55.000000
124      48.000000
125      60.000000
126      67.715686
127      55.000000
128      69.000000
129      69.000000
130      88.000000
131      84.039801
132      75.000000
133      67.715686
134      78.000000
135      80.000000
136      84.039801
137      82.000000
138      73.000000
139      65.000000
140      70.000000
141      78.000000
142      71.000000
143      78.000000
144      70.000000
145      24.000000
146      51.000000
147      59.911111
148      63.000000
149      67.715686
150     120.000000
151     107.000000
152      59.911111
153      67.715686
154      84.000000
155      60.000000
156      60.000000
157      92.000000
158     100.000000
159     134.000000
160      59.911111
161     110.000000
162      95.000000
163      55.000000
164      40.000000
165      62.000000
166      67.715686
167      86.000000
168      62.000000
169      84.039801
170      67.715686
171     141.000000
172      44.000000
173      80.000000
174      47.000000
175      84.000000
176      97.000000
177      67.715686
178      63.000000
179      60.000000
180      67.715686
181      54.000000
182      60.000000
183      63.000000
184      92.000000
185      90.000000
186      59.911111
187      60.000000
188      64.000000
189      41.000000
190      70.000000
191      59.911111
192      68.000000
193      24.000000
194      60.000000
195      24.000000
196      79.000000
197     174.000000
198      92.000000
199      76.000000
200      80.000000
201      75.000000
202      50.000000
203      67.715686
204      50.000000
205      99.000000
206      40.000000
207      67.715686
208      67.715686
209      75.000000
210      67.000000
211      83.000000
212      72.000000
213      43.000000
214      63.515152
215      72.000000
216      65.000000
217      57.000000
218      84.039801
219      43.000000
220      73.000000
221      67.715686
222      85.000000
223      70.000000
224     103.000000
225      21.000000
226      82.000000
227      21.000000
228      70.000000
229      43.000000
230      73.000000
231     174.000000
232      21.000000
233      75.000000
234      67.715686
235      21.000000
236      65.000000
237      59.911111
238      93.000000
239      52.000000
240      75.000000
241      40.000000
242      63.000000
243      75.000000
244      67.715686
245      80.000000
246      69.000000
247      75.000000
248      72.000000
249      59.911111
250      55.000000
251      44.000000
252      65.000000
253      85.000000
254      70.000000
255      66.000000
256      64.000000
257      68.000000
258      80.000000
259      70.000000
260     120.000000
261      69.000000
262      88.000000
263      50.000000
264      30.000000
265      78.000000
266      70.000000
267      60.000000
268      71.000000
269      84.039801
270      84.000000
271      73.000000
272      92.000000
273      80.000000
274      76.000000
275      55.000000
276     129.000000
277     140.000000
278     107.000000
279      83.000000
280      82.000000
281      60.000000
282      34.000000
283      74.000000
284      50.000000
285      35.000000
286      77.000000
287      84.039801
288      67.715686
289      60.000000
290     120.000000
291      55.000000
292      60.000000
293      84.039801
294      80.000000
295      37.000000
296      75.000000
297      66.000000
298      90.000000
299      80.000000
300      90.000000
301      66.000000
302     118.000000
303      70.000000
304      87.000000
305      80.000000
306     116.000000
307      67.715686
308      67.715686
309      90.000000
310      67.715686
311      50.000000
312      65.000000
313     150.000000
314      60.000000
315      71.000000
316      94.000000
317      75.000000
318      90.000000
319      67.715686
320     111.000000
321      99.000000
322      86.000000
323      49.000000
324      96.000000
325      50.000000
326      32.000000
327      80.000000
328      67.715686
329      60.000000
330      67.715686
331      70.000000
332      85.000000
333      59.000000
334      59.000000
335      84.039801
336      86.000000
337      70.000000
338      91.000000
339      66.000000
340      85.000000
341      60.000000
342      67.715686
343      63.000000
344      36.000000
345      65.000000
346      59.911111
347      67.715686
348      36.000000
349      56.000000
350      68.000000
351      67.715686
352      60.000000
353      60.000000
354      60.000000
355     105.000000
356      67.715686
357      44.000000
358      92.000000
359      78.000000
360      59.911111
361      67.715686
362      64.000000
363      21.000000
364      63.515152
365      59.000000
366      67.715686
367     101.000000
368      78.000000
369      84.039801
370      67.715686
371      80.000000
372      50.000000
373      79.000000
374      65.000000
375      67.715686
376      57.000000
377     102.000000
378      88.000000
379      60.000000
380      50.000000
381      60.000000
382      79.000000
383      60.000000
384      84.039801
385      43.000000
386      58.000000
387      72.000000
388      93.000000
389      96.000000
390      50.000000
391      71.000000
392      67.715686
393      84.039801
394      60.000000
395      68.000000
396      60.000000
397      69.000000
398      60.000000
399      65.000000
400      38.000000
401      65.000000
402      60.000000
403      93.000000
404      67.715686
405      84.039801
406      51.000000
407      63.000000
408     109.000000
409      85.000000
410      68.000000
411     100.000000
412      67.715686
413      56.000000
414      59.000000
415      73.000000
416      74.000000
417      86.000000
418      60.000000
419      65.000000
420      78.000000
421      63.515152
422     100.000000
423      80.000000
424      72.000000
425      60.000000
426      67.715686
427      77.000000
428      64.000000
429     130.000000
430      21.000000
431      60.000000
432      24.000000
433     100.000000
434      21.000000
435      43.000000
436      40.000000
437      50.000000
438      40.000000
439      67.000000
440     105.000000
441      92.000000
442      52.000000
443      53.000000
444      70.000000
445      73.000000
446     137.000000
447      84.039801
448      50.000000
449      50.000000
450      70.000000
451      62.000000
452      84.039801
453      75.000000
454      63.000000
455      80.000000
456      34.000000
457      59.911111
458      67.715686
459      84.039801
460      75.000000
461      60.000000
462      60.000000
463      74.000000
464      60.000000
465      67.715686
466      85.000000
467      79.000000
468      98.000000
469      76.000000
470      84.039801
471      92.000000
472      35.000000
473     110.000000
474      41.000000
475      80.000000
476      75.000000
477     105.000000
478      79.000000
479      50.000000
480      98.000000
481      72.000000
482      50.000000
483      32.000000
484      84.039801
485      80.000000
486      79.000000
487      70.000000
488      60.000000
489      21.000000
490      67.715686
491      79.000000
492     105.000000
493      70.000000
494      50.000000
495      60.000000
496      67.715686
497      60.000000
498      65.000000
499      70.000000
500      21.000000
501      75.000000
502      70.000000
503     100.000000
504      24.000000
505      60.000000
506      80.000000
507      75.000000
508      60.000000
509      80.000000
510      75.000000
511      40.000000
512      70.000000
513      71.000000
514      55.000000
515      94.000000
516      84.039801
517      79.000000
518      59.911111
519      53.000000
520      60.000000
521      90.000000
522      50.000000
523     130.000000
524      95.000000
525      62.000000
526      70.000000
527      67.000000
528      58.000000
529      59.911111
530      85.000000
531      60.000000
532      60.000000
533      50.000000
534      74.000000
535      70.000000
536      57.000000
537      63.515152
538      67.715686
539      67.715686
540      85.000000
541      63.515152
542      78.000000
543      34.000000
544      58.000000
545      84.039801
546      70.000000
547      54.000000
548      49.000000
549      75.000000
550      53.000000
551      50.000000
552      87.000000
553      67.000000
554      85.000000
555      58.000000
556      69.000000
557      60.000000
558      57.000000
559      67.715686
560      67.715686
561      77.000000
562      63.000000
563      66.000000
564      59.911111
565      66.000000
566      77.000000
567      70.000000
568      79.000000
569      84.039801
570      74.000000
571      60.000000
572      83.000000
573      76.000000
574      70.000000
575      80.000000
576      52.000000
577      96.000000
578      34.000000
579      81.000000
580      59.911111
581      98.000000
582      81.000000
583      75.000000
584      51.000000
585      88.000000
586      55.000000
587      74.000000
588      65.000000
589      50.000000
590      64.000000
591      97.000000
592      60.000000
593      67.715686
594      88.000000
595      69.000000
596      60.000000
597      53.000000
598      80.000000
599      24.000000
600      74.000000
601      50.000000
602      80.000000
603      30.000000
604      88.000000
605      85.000000
606      82.000000
607      78.000000
608      78.000000
609      61.000000
610      67.715686
611      63.515152
612      67.715686
613      70.000000
614      21.000000
615      80.000000
616      67.715686
617      59.000000
618      90.000000
619      85.000000
620      45.000000
621      90.000000
622      71.000000
623      67.715686
624      80.000000
625      87.000000
626      67.715686
627      80.000000
628      70.000000
629      82.000000
630      50.000000
631      34.000000
632      85.000000
633      80.000000
634      64.000000
635      60.000000
636      51.000000
637      50.000000
638      67.000000
639      53.000000
640      62.000000
641      67.715686
642      75.000000
643      80.000000
644      85.000000
645      84.039801
646      60.000000
647      85.000000
648      70.000000
649      21.000000
650      65.000000
651      60.000000
652      70.000000
653      60.000000
654      91.000000
655      21.000000
656      72.000000
657      60.000000
658      78.000000
659      75.000000
660      59.911111
661      52.000000
662     120.000000
663      90.000000
664      49.000000
665     106.000000
666      67.715686
667      65.000000
668      84.039801
669      80.000000
670      64.000000
671      54.000000
672      67.715686
673     110.000000
674      80.000000
675      24.000000
676      60.000000
677      52.000000
678      80.000000
679      67.715686
680      50.000000
681      55.000000
682      67.715686
683      90.000000
684      58.000000
685      59.911111
686      84.000000
687      63.515152
688      60.000000
689      61.000000
690      67.715686
691     104.000000
692      42.000000
693      60.000000
694      51.000000
695      54.000000
696      50.000000
697      57.000000
698      65.000000
699      59.000000
700      85.000000
701      80.000000
702      82.000000
703      76.000000
704      70.000000
705      70.000000
706      59.911111
707      48.000000
708      65.000000
709      67.715686
710      56.000000
711      66.000000
712      40.000000
713      60.000000
714      59.911111
715      78.000000
716      60.000000
717      80.000000
718      96.000000
719      69.000000
720      59.911111
721      67.715686
722      70.000000
723      60.000000
724      86.000000
725      60.000000
726      84.039801
727      64.000000
728      85.000000
729      52.000000
730      39.000000
731      73.000000
732      75.000000
733      80.000000
734      84.039801
735      60.000000
736      60.000000
737      72.000000
738      60.000000
739      65.000000
740      60.000000
741      65.000000
742      65.000000
743      70.000000
744      41.000000
745      67.715686
746      67.715686
747      65.000000
748      59.000000
749      50.000000
750      55.000000
751      67.715686
752      79.000000
753      80.000000
754      61.000000
755      34.000000
756      68.000000
757      59.911111
758      24.000000
759      65.000000
760      70.000000
761      60.000000
762      72.000000
763      82.000000
764      30.000000
765      75.000000
766      80.000000
767      75.000000
768      70.000000
769      47.000000
770      59.911111
771      67.000000
772      94.000000
773      70.000000
774     110.000000
775      32.000000
776      86.000000
777     100.000000
778      60.000000
779      78.000000
780      63.000000
781      65.000000
782      67.000000
783      84.039801
784      35.000000
785      67.715686
786      60.000000
787      76.000000
788      50.000000
789      67.715686
790      43.000000
791      84.039801
792      92.000000
793      76.000000
794      84.039801
795      70.000000
796      71.000000
797      57.000000
798     104.000000
799      60.000000
800      79.000000
801      40.000000
802      63.000000
803     107.000000
804      75.000000
805      91.000000
806      75.000000
807     144.000000
808      85.000000
809      90.000000
810      78.000000
811      67.715686
812      66.000000
813      75.000000
814      45.000000
815      48.000000
816      84.039801
817      59.911111
818      80.000000
819      44.000000
820      72.000000
821      60.000000
822      84.039801
823      60.000000
824      81.000000
825     114.000000
826      50.000000
827      65.000000
828      59.911111
829      24.000000
830      80.000000
831      30.000000
832      44.000000
833     100.000000
834      75.000000
835      60.000000
836      90.000000
837      21.000000
838      75.000000
839      70.000000
840      67.715686
841      60.000000
842      82.000000
843      80.000000
844     100.000000
845      59.911111
846      75.000000
847      36.000000
848      75.000000
849      80.000000
850      36.000000
851      67.715686
852      53.000000
853      84.039801
854     102.000000
855      84.039801
856      67.715686
857      65.000000
858      80.000000
859      84.039801
860      55.000000
861      75.000000
862      81.000000
863      70.000000
864      72.000000
865      67.715686
866      67.000000
867      85.000000
868      84.039801
869      80.000000
870      60.000000
871      70.000000
872      74.000000
873      60.000000
874      52.000000
875      75.000000
876      94.000000
877      74.000000
878      88.000000
879      59.911111
880      60.000000
881      44.000000
882      84.039801
883      60.000000
884      65.000000
885      50.000000
886      70.000000
887      59.000000
888      95.000000
889     128.000000
890      60.000000
891      70.000000
892      70.000000
893      67.715686
894      64.000000
895      71.000000
896      50.000000
897      64.000000
898     100.000000
899      65.000000
900      67.715686
901      64.000000
902      63.000000
903      50.000000
904      67.715686
905      80.000000
906     116.000000
907      86.000000
908      67.715686
909     149.000000
910      80.000000
911      59.911111
912      51.000000
913      82.000000
914      30.000000
915      21.000000
916      50.000000
917      67.715686
918     103.000000
919      87.000000
920      70.000000
921      67.000000
922      65.000000
923      50.000000
924      79.000000
925      84.039801
926      93.000000
927      67.715686
928      67.715686
929      84.039801
930      73.000000
931      70.000000
932      84.000000
933      63.000000
934     313.000000
935      52.000000
936      67.000000
937      75.000000
938      73.000000
939      67.715686
940      55.000000
941      63.515152
942      42.000000
943     100.000000
944      59.911111
945      98.000000
946      70.000000
947      85.000000
948      65.000000
949      78.000000
950      60.000000
951      60.000000
952      60.000000
953      67.715686
954      35.000000
955      82.000000
956      24.000000
957      70.000000
958      65.000000
959      24.000000
960      50.000000
961      84.039801
962      24.000000
963     122.000000
964      80.000000
965      65.000000
966     130.000000
967      67.715686
968      50.000000
969      75.000000
970      60.000000
971      36.000000
972      55.000000
973      95.000000
974      60.000000
975      63.515152
976      51.000000
977      35.000000
978      68.000000
979      80.000000
980      84.039801
981      98.000000
982      43.000000
983      84.039801
984      75.000000
985      68.000000
986      59.000000
987      83.000000
988      67.715686
989      65.000000
990      82.000000
991     121.000000
992      80.000000
993      68.000000
994      96.000000
995      51.000000
996      67.715686
997      67.715686
998      60.000000
999      64.000000
1000     74.000000
1001     60.000000
1002     75.000000
1003     84.039801
1004     43.000000
1005     65.000000
1006     67.715686
1007     21.000000
1008     43.000000
1009     60.000000
1010    115.000000
1011     75.000000
1012     55.000000
1013     60.000000
1014     60.000000
1015     70.000000
1016     73.000000
1017     59.911111
1018     63.515152
1019     43.000000
1020     60.000000
1021     64.000000
1022     52.000000
1023     43.000000
1024     84.039801
1025     70.000000
1026     73.000000
1027     71.000000
1028     79.000000
1029     21.000000
1030     67.715686
1031    102.000000
1032     84.039801
1033     67.715686
1034     50.000000
1035     59.911111
1036     89.000000
1037     67.715686
1038     21.000000
1039     21.000000
1040     88.000000
1041     67.715686
1042     34.000000
1043     86.000000
1044     80.000000
1045     59.911111
1046     85.000000
1047     57.000000
1048    100.000000
1049     60.000000
1050     73.000000
1051    103.000000

In [20]:
df.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [21]:
l3 = df_drop_clm["GarageQual"].value_counts().keys()
l3

Index(['TA', 'Fa', 'Gd', 'Ex', 'Po'], dtype='object', name='GarageQual')

In [22]:
df_gar1 = df_drop_clm.loc[df_drop_clm["GarageQual"] == "TA", "GarageYrBlt"]
df_gar1

0       2003.0
1       1976.0
2       2001.0
3       1998.0
4       2000.0
5       1993.0
6       2004.0
7       1973.0
10      1965.0
11      2005.0
12      1962.0
13      2006.0
14      1960.0
15      1991.0
16      1970.0
17      1967.0
18      2004.0
19      1958.0
20      2005.0
21      1930.0
22      2002.0
23      1976.0
24      1968.0
25      2007.0
26      2005.0
27      2008.0
28      1957.0
30      1920.0
31      1966.0
32      2007.0
33      1959.0
34      2005.0
35      2004.0
36      1995.0
37      1954.0
38      1953.0
40      1965.0
41      1959.0
42      1983.0
43      1977.0
44      1959.0
45      2005.0
46      2003.0
47      2006.0
49      1966.0
50      1997.0
51      1985.0
52      1963.0
53      1981.0
54      1962.0
55      1964.0
56      1999.0
57      2004.0
58      2006.0
59      1973.0
60      2006.0
61      1935.0
62      2006.0
63      1990.0
64      1998.0
65      2004.0
66      1970.0
67      2003.0
68      1945.0
69      1953.0
70      1973.0
71      1987.0
72      1998.0
73      1989.0
74      1915.0
75      1973.0
76      1956.0
77      1948.0
79      1966.0
80      1968.0
81      1998.0
82      2007.0
83      1974.0
84      1995.0
85      1991.0
86      2005.0
87      2009.0
90      1950.0
91      1961.0
92      1921.0
93      1900.0
94      1997.0
95      1993.0
96      1999.0
97      1965.0
100     1977.0
101     1985.0
102     1979.0
103     2009.0
104     1951.0
105     2003.0
107     1948.0
109     1977.0
110     1954.0
111     2000.0
112     2007.0
113     1953.0
114     1945.0
115     1999.0
116     1962.0
117     2007.0
118     1990.0
119     2005.0
120     1969.0
121     1979.0
122     1958.0
123     1993.0
124     1979.0
126     1977.0
128     1966.0
129     1998.0
130     1966.0
131     2000.0
132     1974.0
133     2001.0
134     1968.0
135     1970.0
136     1967.0
137     1989.0
138     1999.0
139     1997.0
141     2005.0
142     2000.0
143     1999.0
144     1963.0
145     2004.0
147     2001.0
150     1975.0
151     2007.0
152     1971.0
153     1960.0
156     1950.0
157     2009.0
158     2004.0
159     2006.0
160     1984.0
161     2003.0
162     2005.0
164     1926.0
166     1955.0
167     2007.0
168     2004.0
169     1981.0
170     1991.0
171     1960.0
173     1961.0
174     1986.0
175     1950.0
176     1988.0
177     1958.0
178     2009.0
180     2000.0
182     1957.0
183     2003.0
184     1986.0
186     1990.0
188     1979.0
189     2001.0
190     1932.0
191     1972.0
192     1999.0
193     2004.0
194     1989.0
195     1976.0
196     2007.0
197     1918.0
199     2004.0
200     2003.0
201     1980.0
202     1924.0
203     2004.0
204     1948.0
205     1990.0
206     1962.0
207     1960.0
208     1988.0
209     1964.0
211     2009.0
212     2009.0
213     1996.0
214     1977.0
215     1957.0
216     2004.0
217     1940.0
218     1939.0
219     2005.0
220     2006.0
221     2002.0
222     1975.0
223     1989.0
224     2003.0
225     1991.0
226     1995.0
227     1987.0
228     1974.0
229     2005.0
230     1959.0
231     1995.0
232     1972.0
233     1976.0
234     2002.0
235     1971.0
236     2004.0
237     1993.0
238     2007.0
239     1949.0
240     2008.0
243     1980.0
244     1994.0
245     1988.0
247     1954.0
248     2003.0
249     1958.0
251     2006.0
252     2004.0
253     1964.0
254     1957.0
255     1999.0
256     2003.0
257     2006.0
258     2001.0
259     1956.0
260     1991.0
261     2007.0
262     1978.0
263     1974.0
264     1965.0
265     1981.0
266     1997.0
267     1939.0
269     1987.0
270     2006.0
271     1954.0
272     1999.0
273     1958.0
274     1982.0
275     1978.0
276     2003.0
277     1951.0
278     2007.0
279     1977.0
280     1989.0
281     2006.0
282     2008.0
283     2008.0
284     1992.0
285     2006.0
286     1962.0
288     1970.0
289     2003.0
292     1949.0
293     1977.0
294     1953.0
295     1984.0
296     1950.0
297     1997.0
298     1968.0
299     1950.0
300     1953.0
301     1998.0
302     2001.0
303     1975.0
304     2003.0
305     2004.0
306     1990.0
308     1961.0
309     2003.0
310     1993.0
311     1948.0
312     1939.0
313     1965.0
315     2004.0
316     1983.0
317     2006.0
318     1993.0
319     1980.0
320     2006.0
321     2004.0
322     1987.0
324     1961.0
325     1941.0
326     1993.0
327     1960.0
328     1930.0
330     2002.0
331     1958.0
332     2003.0
333     2004.0
334     1998.0
335     1965.0
336     2005.0
337     2002.0
338     1984.0
339     1958.0
340     2002.0
341     1950.0
342     1949.0
343     2005.0
344     1976.0
345     1939.0
346     1960.0
347     1960.0
348     2003.0
349     2006.0
350     2007.0
351     1986.0
352     1941.0
353     2005.0
354     1940.0
355     1995.0
356     1992.0
357     1976.0
358     1958.0
359     1998.0
360     1978.0
361     1940.0
362     2003.0
363     1972.0
364     1976.0
365     1964.0
366     1963.0
367     1962.0
368     1954.0
369     1997.0
370     2000.0
371     1991.0
372     1984.0
373     1953.0
374     2003.0
376     1998.0
377     2004.0
378     2010.0
379     2000.0
380     1924.0
381     2006.0
382     2006.0
384     1992.0
385     2004.0
387     1977.0
388     1999.0
389     2008.0
390     1978.0
391     2001.0
392     1959.0
394     1940.0
395     1956.0
396     1985.0
397     1962.0
399     2007.0
400     1996.0
401     2005.0
402     1940.0
403     1998.0
404     1995.0
405     1993.0
406     1936.0
407     1960.0
408     2006.0
409     2008.0
410     1958.0
411     1955.0
412     2009.0
413     1927.0
414     1993.0
415     2007.0
416     1978.0
417     1918.0
418     1940.0
419     1968.0
420     1997.0
421     1977.0
422     1954.0
423     1998.0
424     1956.0
425     1947.0
426     1989.0
427     1964.0
428     2007.0
429     1988.0
430     1971.0
432     1971.0
433     1997.0
435     1996.0
436     1990.0
437     1926.0
439     2005.0
440     2008.0
442     1930.0
443     2007.0
444     1994.0
445     1956.0
446     1966.0
447     1998.0
448     1937.0
449     1981.0
451     1975.0
452     1996.0
453     2008.0
454     1976.0
455     1973.0
457     1954.0
458     1925.0
459     1950.0
460     2009.0
461     1971.0
462     1965.0
463     1939.0
465     2004.0
466     1970.0
467     1942.0
468     2006.0
469     1993.0
470     1985.0
471     1977.0
472     2005.0
473     2006.0
474     2000.0
475     1996.0
476     1997.0
477     2006.0
478     2007.0
479     1995.0
480     2004.0
481     2003.0
483     1998.0
484     1963.0
485     1950.0
486     1965.0
487     1971.0
488     1970.0
489     1970.0
490     1976.0
491     1941.0
492     2006.0
493     1964.0
494     1938.0
496     1992.0
497     1925.0
498     1967.0
499     1958.0
500     1973.0
501     2005.0
503     1959.0
504     1974.0
505     1952.0
506     1993.0
507     2009.0
508     1928.0
509     1959.0
510     1951.0
511     2005.0
512     1964.0
513     1983.0
515     2009.0
516     1972.0
517     1996.0
518     1998.0
519     1926.0
521     1957.0
522     1950.0
523     2007.0
524     1996.0
525     2005.0
526     1956.0
527     2008.0
529     1975.0
530     1988.0
531     1920.0
532     1967.0
534     2004.0
536     1998.0
537     1980.0
538     1968.0
539     2001.0
540     2006.0
541     2000.0
542     1998.0
543     1998.0
544     2006.0
545     1988.0
546     1950.0
547     1987.0
548     1963.0
549     2003.0
550     1977.0
551     1957.0
552     2006.0
553     2002.0
554     2003.0
555     1922.0
556     1957.0
557     1994.0
558     1996.0
559     2003.0
560     1957.0
561     1975.0
563     1955.0
564     1992.0
565     1920.0
566     2005.0
567     2004.0
569     1979.0
570     1987.0
571     1959.0
572     2009.0
573     2000.0
574     1971.0
575     1947.0
576     1928.0
577     1966.0
578     2007.0
580     1960.0
581     2009.0
584     1935.0
585     2005.0
586     1961.0
587     1996.0
588     1968.0
589     1988.0
590     2004.0
591     2008.0
592     1985.0
593     2003.0
594     1981.0
595     2005.0
596     1930.0
597     2006.0
598     1977.0
599     1980.0
600     2003.0
601     1979.0
602     1992.0
603     2004.0
604     2002.0
605     1965.0
606     2000.0
607     1948.0
608     1934.0
609     1961.0
610     2000.0
611     1978.0
612     2001.0
615     1963.0
616     2002.0
617     1962.0
618     2007.0
619     2003.0
621     1974.0
622     1986.0
623     2000.0
624     1972.0
625     1962.0
626     1960.0
627     1955.0
628     1969.0
629     1964.0
631     2006.0
632     1977.0
633     1954.0
634     1980.0
637     1954.0
639     2006.0
640     2003.0
641     2001.0
642     1972.0
643     1969.0
644     2009.0
645     1979.0
646     1950.0
647     1953.0
648     1966.0
650     2007.0
652     1996.0
653     1906.0
654     1995.0
655     1971.0
656     1959.0
657     1931.0
658     1948.0
659     1968.0
660     1976.0
661     1994.0
662     1968.0
663     1974.0
664     2005.0
665     2000.0
666     1965.0
667     1994.0
668     1999.0
669     1922.0
670     2005.0
671     1930.0
672     1977.0
673     1957.0
674     1965.0
675     1978.0
678     2008.0
679     1963.0
680     1980.0
681     1968.0
682     1996.0
683     2002.0
684     1998.0
685     1984.0
686     2007.0
687     2004.0
688     2007.0
689     2005.0
690     2004.0
691     1994.0
692     1989.0
693     1968.0
694     1995.0
695     1987.0
696     1921.0
697     1952.0
698     1973.0
699     2004.0
700     2002.0
701     1969.0
702     2006.0
703     1999.0
704     2004.0
706     1971.0
707     2006.0
708     2007.0
709     1966.0
711     1964.0
712     1988.0
713     1970.0
714     1976.0
715     1974.0
716     1996.0
717     1973.0
718     1993.0
719     1969.0
720     1985.0
721     2004.0
722     1994.0
723     1958.0
724     2007.0
725     1989.0
726     1988.0
727     2007.0
728     1968.0
729     1962.0
730     1995.0
731     2003.0
732     1998.0
733     1961.0
734     1968.0
735     1914.0
736     1949.0
737     2005.0
739     2004.0
740     1910.0
741     1962.0
742     2000.0
743     1997.0
744     1993.0
745     1994.0
746     2000.0
747     1950.0
748     1996.0
749     1945.0
751     2003.0
752     1997.0
753     2005.0
754     1969.0
755     1999.0
756     2007.0
757     1978.0
758     1999.0
759     1995.0
761     1965.0
762     2009.0
763     1999.0
764     1995.0
765     2008.0
766     1988.0
767     1989.0
768     2004.0
769     2003.0
770     1983.0
771     1951.0
772     1976.0
773     1958.0
774     2006.0
775     1998.0
776     2005.0
777     1974.0
778     1977.0
779     1977.0
780     1995.0
781     1992.0
782     2001.0
783     1978.0
785     1967.0
786     1961.0
787     2004.0
789     1966.0
790     2005.0
791     1976.0
792     1997.0
793     2007.0
794     1994.0
795     1980.0
796     1977.0
797     1953.0
798     2009.0
799     1939.0
800     1997.0
801     1957.0
802     2005.0
803     2009.0
804     1954.0
805     2008.0
806     1967.0
807     1923.0
808     1966.0
810     1974.0
811     2004.0
812     1952.0
813     1958.0
814     1955.0
815     1998.0
816     1954.0
817     2002.0
818     1971.0
819     2010.0
820     2003.0
821     1974.0
822     2003.0
823     1940.0
824     2006.0
825     2007.0
827     2001.0
828     1967.0
829     2005.0
830     1957.0
831     2005.0
832     2003.0
833     1964.0
834     1961.0
835     1996.0
836     1948.0
837     1973.0
838     1999.0
839     1946.0
840     1934.0
844     1949.0
845     1975.0
846     1993.0
847     1972.0
849     1976.0
850     2003.0
851     2003.0
852     1941.0
853     1964.0
854     1955.0
855     1962.0
856     1981.0
857     1994.0
858     1976.0
859     1968.0
860     1925.0
861     1965.0
862     1986.0
863     1959.0
864     2008.0
865     1973.0
866     2007.0
867     1961.0
868     1979.0
869     1993.0
870     1962.0
871     1998.0
872     1953.0
873     1949.0
874     1941.0
875     2007.0
876     1963.0
877     2004.0
878     1987.0
879     1978.0
880     2005.0
881     1990.0
882     1993.0
883     1997.0
884     1967.0
885     1999.0
886     2005.0
887     1955.0
888     1970.0
889     1953.0
890     2003.0
891     1978.0
892     1963.0
893     1954.0
894     1979.0
895     1963.0
896     1936.0
897     1979.0
898     2009.0
899     1961.0
900     1979.0
901     1968.0
902     2003.0
903     2006.0
904     1967.0
905     1954.0
906     2006.0
908     1983.0
909     2005.0
910     1960.0
911     1978.0
912     1925.0
913     1949.0
914     2009.0
915     1970.0
916     1958.0
917     1956.0
918     1991.0
919     1990.0
920     1994.0
922     2005.0
923     1993.0
924     1980.0
925     1977.0
926     2003.0
927     1968.0
928     2001.0
929     1997.0
930     2007.0
931     1965.0
932     2006.0
933     2004.0
934     1960.0
935     1953.0
936     2003.0
937     2005.0
938     2006.0
939     1940.0
940     1976.0
941     1999.0
943     1967.0
944     1958.0
945     1963.0
946     1959.0
947     2002.0
948     2002.0
949     1972.0
950     1980.0
951     1979.0
952     1974.0
953     1969.0
955     1946.0
956     1980.0
957     1977.0
958     2003.0
959     1999.0
961     1977.0
962     1976.0
963     2007.0
964     2002.0
965     2005.0
966     1940.0
967     1955.0
969     1958.0
971     2003.0
972     1979.0
973     2007.0
974     1997.0
975     2000.0
977     2007.0
978     1999.0
979     1963.0
980     1961.0
981     1998.0
982     2007.0
983     2002.0
984     1977.0
985     1950.0
987     2010.0
988     1976.0
989     2006.0
990     1997.0
991     1925.0
992     1964.0
993     2005.0
994     2008.0
995     1946.0
996     1961.0
997     1970.0
998     1922.0
999     2006.0
1000    1956.0
1002    2006.0
1003    1976.0
1004    2005.0
1005    1977.0
1006    1970.0
1007    1970.0
1008    2004.0
1010    1948.0
1012    1923.0
1013    1956.0
1014    1948.0
1015    2001.0
1016    1996.0
1017    1984.0
1018    1991.0
1019    2005.0
1020    2005.0
1021    2006.0
1023    2005.0
1024    1976.0
1025    1980.0
1026    1960.0
1027    2008.0
1028    1941.0
1029    1972.0
1031    1970.0
1032    1993.0
1033    2002.0
1035    1957.0
1036    2008.0
1037    2001.0
1039    1970.0
1040    1957.0
1041    1966.0
1042    2005.0
1043    1990.0
1044    1981.0
1045    1955.0
1046    2005.0
1047    1996.0
1048    1960.0
1049    1946.0
1050    2007.0
1051    2007.0
1052    1964.0
1053    1957.0
1054    2002.0
1055    1976.0
1056    2005.0
1057    1994.0
1058    2008.0
1059    1977.0
1060    2001.0
1061    1994.0
1062    1945.0
1063    1976.0
1064    1966.0
1065    1996.0
1066    1993.0
1067    1964.0
1068    1973.0
1069    1985.0
1070    1956.0
1071    1968.0
1072    1954.0
1073    1977.0
1074    2006.0
1075    1940.0
1076    1950.0
1077    1969.0
1078    2004.0
1079    1996.0
1080    1971.0
1081    1963.0
1082    2002.0
1083    1964.0
1084    1995.0
1085    1992.0
1086    1973.0
1087    2005.0
1088    2004.0
1089    2005.0
1090    1987.0
1091    1999.0
1092    1925.0
1093    1977.0
1094    1956.0
1095    2006.0
1097    1987.0
1098    1936.0
1099    1978.0
1100    1930.0
1101    1981.0
1102    1960.0
1103    1954.0
1104    1970.0
1105    1994.0
1106    1990.0
1107    2006.0
1108    2000.0
1109    2004.0
1110    1995.0
1111    1976.0
1112    1957.0
1113    1953.0
1114    1955.0
1115    2007.0
1116    2002.0
1117    1967.0
1118    1958.0
1119    1959.0
1120    1920.0
1121    2005.0
1122    1956.0
1124    1992.0
1126    2007.0
1127    2004.0
1128    2004.0
1129    1980.0
1130    1981.0
1133    1995.0
1134    1997.0
1135    1926.0
1136    1950.0
1138    1977.0
1139    1972.0
1140    1988.0
1141    1976.0
1142    2006.0
1144    1941.0
1145    1928.0
1146    1985.0
1147    1941.0
1148    1982.0
1149    1930.0
1150    1950.0
1151    1959.0
1152    1956.0
1153    2002.0
1154    1965.0
1155    1976.0
1156    1965.0
1157    2008.0
1158    2008.0
1160    1978.0
1161    1993.0
1162    1968.0
1164    1978.0
1165    2009.0
1166    2008.0
1167    2000.0
1168    1935.0
1169    1995.0
1170    1977.0
1171    1958.0
1172    2006.0
1174    1932.0
1175    1992.0
1176    1984.0
1177    1926.0
1180    1990.0
1181    2008.0
1182    1996.0
1183    1970.0
1184    1963.0
1185    1965.0
1187    1994.0
1188    2002.0
1189    1999.0
1190    1975.0
1191    1999.0
1192    1925.0
1193    1999.0
1194    1969.0
1195    2005.0
1196    2006.0
1197    1916.0
1198    2001.0
1199    1974.0
1200    1972.0
1201    1998.0
1202    1960.0
1203    2000.0
1204    1975.0
1205    1990.0
1206    1966.0
1207    2003.0
1208    1980.0
1209    2006.0
1210    1992.0
1211    1988.0
1212    1941.0
1213    1965.0
1214    1962.0
1215    1966.0
1216    1978.0
1217    2009.0
1220    1964.0
1221    1968.0
1222    1949.0
1223    1951.0
1224    2004.0
1225    1958.0
1226    2007.0
1227    1992.0
1228    2008.0
1229    1960.0
1230    1977.0
1231    1962.0
1232    1962.0
1233    1959.0
1236    2003.0
1237    2004.0
1238    2005.0
1239    2006.0
1240    2003.0
1241    2007.0
1242    1974.0
1243    2006.0
1244    1931.0
1245    1984.0
1246    2005.0
1247    1976.0
1249    1950.0
1250    1968.0
1251    2003.0
1252    1968.0
1253    1974.0
1254    2003.0
1255    1978.0
1256    1994.0
1258    2005.0
1259    1969.0
1260    1999.0
1261    1956.0
1262    1957.0
1263    1940.0
1264    1998.0
1265    1999.0
1266    1960.0
1267    2009.0
1268    1982.0
1269    1958.0
1270    1979.0
1271    1968.0
1272    1965.0
1273    1959.0
1274    1985.0
1275    1948.0
1276    1972.0
1277    1967.0
1278    2002.0
1279    1980.0
1280    2002.0
1282    1977.0
1284    1969.0
1285    1939.0
1286    1963.0
1287    1964.0
1288    2000.0
1289    2006.0
1290    1964.0
1291    1972.0
1292    1985.0
1293    1976.0
1294    1957.0
1295    1968.0
1296    1963.0
1297    2005.0
1298    2008.0
1299    1959.0
1300    1999.0
1301    1942.0
1302    1994.0
1303    2005.0
1304    2004.0
1305    2006.0
1306    2005.0
1307    2000.0
1308    1948.0
1309    1991.0
1310    1959.0
1311    2005.0
1313    1999.0
1314    1956.0
1315    1969.0
1316    2008.0
1317    2006.0
1318    2001.0
1319    1954.0
1320    1957.0
1321    1955.0
1322    1992.0
1324    2007.0
1327    1982.0
1329    1998.0
1330    2006.0
1331    1976.0
1333    1951.0
1334    1970.0
1335    1977.0
1336    1973.0
1338    2002.0
1339    1972.0
1340    1974.0
1341    2004.0
1342    2002.0
1344    2006.0
1345    1997.0
1347    2006.0
1348    1998.0
1350    1969.0
1351    1962.0
1352    1999.0
1353    1996.0
1354    2000.0
1355    1968.0
1356    1966.0
1357    1971.0
1358    2000.0
1359    2004.0
1360    1998.0
1361    2005.0
1362    1920.0
1363    2007.0
1364    2005.0
1365    2000.0
1366    1999.0
1367    1977.0
1368    2003.0
1369    2003.0
1370    1967.0
1371    1955.0
1372    1998.0
1373    2001.0
1374    2005.0
1375    2007.0
1377    1977.0
1378    1973.0
1379    2007.0
1380    1938.0
1381    1970.0
1382    1989.0
1383    2007.0
1384    1939.0
1385    1922.0
1386    1978.0
1387    1916.0
1388    2006.0
1389    2003.0
1390    2000.0
1391    1967.0
1392    1967.0
1394    2006.0
1395    2005.0
1396    1966.0
1398    1950.0
1400    1929.0
1401    2004.0
1402    2006.0
1403    2007.0
1404    1998.0
1405    2004.0
1406    1988.0
1408    1966.0
1409    1986.0
1410    2001.0
1411    1950.0
1412    1956.0
1413    2005.0
1414    1922.0
1415    2007.0
1416    1971.0
1417    1998.0
1418    1962.0
1419    1969.0
1420    1968.0
1421    1977.0
1422    2003.0
1424    1970.0
1425    1960.0
1426    1994.0
1427    1962.0
1428    1940.0
1429    1981.0
1430    2005.0
1431    1976.0
1433    2000.0
1434    1977.0
1435    1962.0
1436    1974.0
1437    2008.0
1438    1957.0
1439    1979.0
1440    1993.0
1441    2004.0
1442    2008.0
1444    2004.0
1445    1990.0
1446    1962.0
1447    1995.0
1451    2008.0
1452    2005.0
1454    2004.0
1455    1999.0
1456    1978.0
1457    1941.0
1458    1950.0
1459    1965.0
Name: GarageYrBlt, dtype: float64

In [23]:
for i in l3:
    df_drop_clm.loc[df_drop_clm["GarageQual"] == i, "GarageYrBlt"] = df_drop_clm.loc[df_drop_clm["GarageQual"] == i, "GarageYrBlt"].rep(np.nan, df_drop_clm.loc[df_drop_clm["GarageQual"] == i, "GarageYrBlt"].mean())

TypeError: NDFrame.fillna() takes from 1 to 2 positional arguments but 3 were given

In [24]:
for i in l3:
    df_drop_clm.loc[df_drop_clm["GarageQual"] == i, "GarageYrBlt"] = \
        df_drop_clm.loc[df_drop_clm["GarageQual"] == i, "GarageYrBlt"] \
        .fillna(df_drop_clm.loc[df_drop_clm["GarageQual"] == i, "GarageYrBlt"].mean())

In [26]:
df_drop_clm["GarageYrBlt"]

0       2003.0
1       1976.0
2       2001.0
3       1998.0
4       2000.0
5       1993.0
6       2004.0
7       1973.0
8       1931.0
9       1939.0
10      1965.0
11      2005.0
12      1962.0
13      2006.0
14      1960.0
15      1991.0
16      1970.0
17      1967.0
18      2004.0
19      1958.0
20      2005.0
21      1930.0
22      2002.0
23      1976.0
24      1968.0
25      2007.0
26      2005.0
27      2008.0
28      1957.0
29      1920.0
30      1920.0
31      1966.0
32      2007.0
33      1959.0
34      2005.0
35      2004.0
36      1995.0
37      1954.0
38      1953.0
39         NaN
40      1965.0
41      1959.0
42      1983.0
43      1977.0
44      1959.0
45      2005.0
46      2003.0
47      2006.0
48         NaN
49      1966.0
50      1997.0
51      1985.0
52      1963.0
53      1981.0
54      1962.0
55      1964.0
56      1999.0
57      2004.0
58      2006.0
59      1973.0
60      2006.0
61      1935.0
62      2006.0
63      1990.0
64      1998.0
65      2004.0
66      1970.0
67      2003.0
68      1945.0
69      1953.0
70      1973.0
71      1987.0
72      1998.0
73      1989.0
74      1915.0
75      1973.0
76      1956.0
77      1948.0
78         NaN
79      1966.0
80      1968.0
81      1998.0
82      2007.0
83      1974.0
84      1995.0
85      1991.0
86      2005.0
87      2009.0
88         NaN
89         NaN
90      1950.0
91      1961.0
92      1921.0
93      1900.0
94      1997.0
95      1993.0
96      1999.0
97      1965.0
98      1920.0
99         NaN
100     1977.0
101     1985.0
102     1979.0
103     2009.0
104     1951.0
105     2003.0
106     1954.0
107     1948.0
108        NaN
109     1977.0
110     1954.0
111     2000.0
112     2007.0
113     1953.0
114     1945.0
115     1999.0
116     1962.0
117     2007.0
118     1990.0
119     2005.0
120     1969.0
121     1979.0
122     1958.0
123     1993.0
124     1979.0
125        NaN
126     1977.0
127        NaN
128     1966.0
129     1998.0
130     1966.0
131     2000.0
132     1974.0
133     2001.0
134     1968.0
135     1970.0
136     1967.0
137     1989.0
138     1999.0
139     1997.0
140        NaN
141     2005.0
142     2000.0
143     1999.0
144     1963.0
145     2004.0
146     1931.0
147     2001.0
148        NaN
149     1936.0
150     1975.0
151     2007.0
152     1971.0
153     1960.0
154     1923.0
155        NaN
156     1950.0
157     2009.0
158     2004.0
159     2006.0
160     1984.0
161     2003.0
162     2005.0
163        NaN
164     1926.0
165        NaN
166     1955.0
167     2007.0
168     2004.0
169     1981.0
170     1991.0
171     1960.0
172     1987.0
173     1961.0
174     1986.0
175     1950.0
176     1988.0
177     1958.0
178     2009.0
179     1935.0
180     2000.0
181     1920.0
182     1957.0
183     2003.0
184     1986.0
185     1993.0
186     1990.0
187     1916.0
188     1979.0
189     2001.0
190     1932.0
191     1972.0
192     1999.0
193     2004.0
194     1989.0
195     1976.0
196     2007.0
197     1918.0
198        NaN
199     2004.0
200     2003.0
201     1980.0
202     1924.0
203     2004.0
204     1948.0
205     1990.0
206     1962.0
207     1960.0
208     1988.0
209     1964.0
210        NaN
211     2009.0
212     2009.0
213     1996.0
214     1977.0
215     1957.0
216     2004.0
217     1940.0
218     1939.0
219     2005.0
220     2006.0
221     2002.0
222     1975.0
223     1989.0
224     2003.0
225     1991.0
226     1995.0
227     1987.0
228     1974.0
229     2005.0
230     1959.0
231     1995.0
232     1972.0
233     1976.0
234     2002.0
235     1971.0
236     2004.0
237     1993.0
238     2007.0
239     1949.0
240     2008.0
241        NaN
242     1940.0
243     1980.0
244     1994.0
245     1988.0
246     1910.0
247     1954.0
248     2003.0
249     1958.0
250        NaN
251     2006.0
252     2004.0
253     1964.0
254     1957.0
255     1999.0
256     2003.0
257     2006.0
258     2001.0
259     1956.0
260     1991.0
261     2007.0
262     1978.0
263     1974.0
264     1965.0
265     1981.0
266     1997.0
267     1939.0
268     1966.0
269     1987.0
270     2006.0
271     1954.0
272     1999.0
273     1958.0
274     1982.0
275     1978.0
276     2003.0
277     1951.0
278     2007.0
279     1977.0
280     1989.0
281     2006.0
282     2008.0
283     2008.0
284     1992.0
285     2006.0
286     1962.0
287        NaN
288     1970.0
289     2003.0
290     2006.0
291        NaN
292     1949.0
293     1977.0
294     1953.0
295     1984.0
296     1950.0
297     1997.0
298     1968.0
299     1950.0
300     1953.0
301     1998.0
302     2001.0
303     1975.0
304     2003.0
305     2004.0
306     1990.0
307        NaN
308     1961.0
309     2003.0
310     1993.0
311     1948.0
312     1939.0
313     1965.0
314     1925.0
315     2004.0
316     1983.0
317     2006.0
318     1993.0
319     1980.0
320     2006.0
321     2004.0
322     1987.0
323     1955.0
324     1961.0
325     1941.0
326     1993.0
327     1960.0
328     1930.0
329     1920.0
330     2002.0
331     1958.0
332     2003.0
333     2004.0
334     1998.0
335     1965.0
336     2005.0
337     2002.0
338     1984.0
339     1958.0
340     2002.0
341     1950.0
342     1949.0
343     2005.0
344     1976.0
345     1939.0
346     1960.0
347     1960.0
348     2003.0
349     2006.0
350     2007.0
351     1986.0
352     1941.0
353     2005.0
354     1940.0
355     1995.0
356     1992.0
357     1976.0
358     1958.0
359     1998.0
360     1978.0
361     1940.0
362     2003.0
363     1972.0
364     1976.0
365     1964.0
366     1963.0
367     1962.0
368     1954.0
369     1997.0
370     2000.0
371     1991.0
372     1984.0
373     1953.0
374     2003.0
375        NaN
376     1998.0
377     2004.0
378     2010.0
379     2000.0
380     1924.0
381     2006.0
382     2006.0
383     1950.0
384     1992.0
385     2004.0
386        NaN
387     1977.0
388     1999.0
389     2008.0
390     1978.0
391     2001.0
392     1959.0
393        NaN
394     1940.0
395     1956.0
396     1985.0
397     1962.0
398     1920.0
399     2007.0
400     1996.0
401     2005.0
402     1940.0
403     1998.0
404     1995.0
405     1993.0
406     1936.0
407     1960.0
408     2006.0
409     2008.0
410     1958.0
411     1955.0
412     2009.0
413     1927.0
414     1993.0
415     2007.0
416     1978.0
417     1918.0
418     1940.0
419     1968.0
420     1997.0
421     1977.0
422     1954.0
423     1998.0
424     1956.0
425     1947.0
426     1989.0
427     1964.0
428     2007.0
429     1988.0
430     1971.0
431        NaN
432     1971.0
433     1997.0
434        NaN
435     1996.0
436     1990.0
437     1926.0
438     1990.0
439     2005.0
440     2008.0
441        NaN
442     1930.0
443     2007.0
444     1994.0
445     1956.0
446     1966.0
447     1998.0
448     1937.0
449     1981.0
450     1932.0
451     1975.0
452     1996.0
453     2008.0
454     1976.0
455     1973.0
456     1916.0
457     1954.0
458     1925.0
459     1950.0
460     2009.0
461     1971.0
462     1965.0
463     1939.0
464        NaN
465     2004.0
466     1970.0
467     1942.0
468     2006.0
469     1993.0
470     1985.0
471     1977.0
472     2005.0
473     2006.0
474     2000.0
475     1996.0
476     1997.0
477     2006.0
478     2007.0
479     1995.0
480     2004.0
481     2003.0
482     1915.0
483     1998.0
484     1963.0
485     1950.0
486     1965.0
487     1971.0
488     1970.0
489     1970.0
490     1976.0
491     1941.0
492     2006.0
493     1964.0
494     1938.0
495        NaN
496     1992.0
497     1925.0
498     1967.0
499     1958.0
500     1973.0
501     2005.0
502     1965.0
503     1959.0
504     1974.0
505     1952.0
506     1993.0
507     2009.0
508     1928.0
509     1959.0
510     1951.0
511     2005.0
512     1964.0
513     1983.0
514     1926.0
515     2009.0
516     1972.0
517     1996.0
518     1998.0
519     1926.0
520        NaN
521     1957.0
522     1950.0
523     2007.0
524     1996.0
525     2005.0
526     1956.0
527     2008.0
528        NaN
529     1975.0
530     1988.0
531     1920.0
532     1967.0
533        NaN
534     2004.0
535        NaN
536     1998.0
537     1980.0
538     1968.0
539     2001.0
540     2006.0
541     2000.0
542     1998.0
543     1998.0
544     2006.0
545     1988.0
546     1950.0
547     1987.0
548     1963.0
549     2003.0
550     1977.0
551     1957.0
552     2006.0
553     2002.0
554     2003.0
555     1922.0
556     1957.0
557     1994.0
558     1996.0
559     2003.0
560     1957.0
561     1975.0
562        NaN
563     1955.0
564     1992.0
565     1920.0
566     2005.0
567     2004.0
568     1983.0
569     1979.0
570     1987.0
571     1959.0
572     2009.0
573     2000.0
574     1971.0
575     1947.0
576     1928.0
577     1966.0
578     2007.0
579     1954.0
580     1960.0
581     2009.0
582        NaN
583     1988.0
584     1935.0
585     2005.0
586     1961.0
587     1996.0
588     1968.0
589     1988.0
590     2004.0
591     2008.0
592     1985.0
593     2003.0
594     1981.0
595     2005.0
596     1930.0
597     2006.0
598     1977.0
599     1980.0
600     2003.0
601     1979.0
602     1992.0
603     2004.0
604     2002.0
605     1965.0
606     2000.0
607     1948.0
608     1934.0
609     1961.0
610     2000.0
611     1978.0
612     2001.0
613        NaN
614        NaN
615     1963.0
616     2002.0
617     1962.0
618     2007.0
619     2003.0
620        NaN
621     1974.0
622     1986.0
623     2000.0
624     1972.0
625     1962.0
626     1960.0
627     1955.0
628     1969.0
629     1964.0
630     1937.0
631     2006.0
632     1977.0
633     1954.0
634     1980.0
635        NaN
636        NaN
637     1954.0
638        NaN
639     2006.0
640     2003.0
641     2001.0
642     1972.0
643     1969.0
644     2009.0
645     1979.0
646     1950.0
647     1953.0
648     1966.0
649        NaN
650     2007.0
651     1940.0
652     1996.0
653     1906.0
654     1995.0
655     1971.0
656     1959.0
657     1931.0
658     1948.0
659     1968.0
660     1976.0
661     1994.0
662     1968.0
663     1974.0
664     2005.0
665     2000.0
666     1965.0
667     1994.0
668     1999.0
669     1922.0
670     2005.0
671     1930.0
672     1977.0
673     1957.0
674     1965.0
675     1978.0
676     1920.0
677     1924.0
678     2008.0
679     1963.0
680     1980.0
681     1968.0
682     1996.0
683     2002.0
684     1998.0
685     1984.0
686     2007.0
687     2004.0
688     2007.0
689     2005.0
690     2004.0
691     1994.0
692     1989.0
693     1968.0
694     1995.0
695     1987.0
696     1921.0
697     1952.0
698     1973.0
699     2004.0
700     2002.0
701     1969.0
702     2006.0
703     1999.0
704     2004.0
705        NaN
706     1971.0
707     2006.0
708     2007.0
709     1966.0
710        NaN
711     1964.0
712     1988.0
713     1970.0
714     1976.0
715     1974.0
716     1996.0
717     1973.0
718     1993.0
719     1969.0
720     1985.0
721     2004.0
722     1994.0
723     1958.0
724     2007.0
725     1989.0
726     1988.0
727     2007.0
728     1968.0
729     1962.0
730     1995.0
731     2003.0
732     1998.0
733     1961.0
734     1968.0
735     1914.0
736     1949.0
737     2005.0
738        NaN
739     2004.0
740     1910.0
741     1962.0
742     2000.0
743     1997.0
744     1993.0
745     1994.0
746     2000.0
747     1950.0
748     1996.0
749     1945.0
750        NaN
751     2003.0
752     1997.0
753     2005.0
754     1969.0
755     1999.0
756     2007.0
757     1978.0
758     1999.0
759     1995.0
760     2008.0
761     1965.0
762     2009.0
763     1999.0
764     1995.0
765     2008.0
766     1988.0
767     1989.0
768     2004.0
769     2003.0
770     1983.0
771     1951.0
772     1976.0
773     1958.0
774     2006.0
775     1998.0
776     2005.0
777     1974.0
778     1977.0
779     1977.0
780     1995.0
781     1992.0
782     2001.0
783     1978.0
784        NaN
785     1967.0
786     1961.0
787     2004.0
788     1954.0
789     1966.0
790     2005.0
791     1976.0
792     1997.0
793     2007.0
794     1994.0
795     1980.0
796     1977.0
797     1953.0
798     2009.0
799     1939.0
800     1997.0
801     1957.0
802     2005.0
803     2009.0
804     1954.0
805     2008.0
806     1967.0
807     1923.0
808     1966.0
809     1910.0
810     1974.0
811     2004.0
812     1952.0
813     1958.0
814     1955.0
815     1998.0
816     1954.0
817     2002.0
818     1971.0
819     2010.0
820     2003.0
821     1974.0
822     2003.0
823     1940.0
824     2006.0
825     2007.0
826        NaN
827     2001.0
828     1967.0
829     2005.0
830     1957.0
831     2005.0
832     2003.0
833     1964.0
834     1961.0
835     1996.0
836     1948.0
837     1973.0
838     1999.0
839     1946.0
840     1934.0
841     1983.0
842     1966.0
843        NaN
844     1949.0
845     1975.0
846     1993.0
847     1972.0
848     1908.0
849     1976.0
850     2003.0
851     2003.0
852     1941.0
853     1964.0
854     1955.0
855     1962.0
856     1981.0
857     1994.0
858     1976.0
859     1968.0
860     1925.0
861     1965.0
862     1986.0
863     1959.0
864     2008.0
865     1973.0
866     2007.0
867     1961.0
868     1979.0
869     1993.0
870     1962.0
871     1998.0
872     1953.0
873     1949.0
874     1941.0
875     2007.0
876     1963.0
877     2004.0
878     1987.0
879     1978.0
880     2005.0
881     1990.0
882     1993.0
883     1997.0
884     1967.0
885     1999.0
886     2005.0
887     1955.0
888     1970.0
889     1953.0
890     2003.0
891     1978.0
892     1963.0
893     1954.0
894     1979.0
895     1963.0
896     1936.0
897     1979.0
898     2009.0
899     1961.0
900     1979.0
901     1968.0
902     2003.0
903     2006.0
904     1967.0
905     1954.0
906     2006.0
907     1936.0
908     1983.0
909     2005.0
910     1960.0
911     1978.0
912     1925.0
913     1949.0
914     2009.0
915     1970.0
916     1958.0
917     1956.0
918     1991.0
919     1990.0
920     1994.0
921        NaN
922     2005.0
923     1993.0
924     1980.0
925     1977.0
926     2003.0
927     1968.0
928     2001.0
929     1997.0
930     2007.0
931     1965.0
932     2006.0
933     2004.0
934     1960.0
935     1953.0
936     2003.0
937     2005.0
938     2006.0
939     1940.0
940     1976.0
941     1999.0
942        NaN
943     1967.0
944     1958.0
945     1963.0
946     1959.0
947     2002.0
948     2002.0
949     1972.0
950     1980.0
951     1979.0
952     1974.0
953     1969.0
954        NaN
955     1946.0
956     1980.0
957     1977.0
958     2003.0
959     1999.0
960        NaN
961     1977.0
962     1976.0
963     2007.0
964     2002.0
965     2005.0
966     1940.0
967     1955.0
968        NaN
969     1958.0
970        NaN
971     2003.0
972     1979.0
973     2007.0
974     1997.0
975     2000.0
976        NaN
977     2007.0
978     1999.0
979     1963.0
980     1961.0
981     1998.0
982     2007.0
983     2002.0
984     1977.0
985     1950.0
986     1950.0
987     2010.0
988     1976.0
989     2006.0
990     1997.0
991     1925.0
992     1964.0
993     2005.0
994     2008.0
995     1946.0
996     1961.0
997     1970.0
998     1922.0
999     2006.0
1000    1956.0
1001    1920.0
1002    2006.0
1003    1976.0
1004    2005.0
1005    1977.0
1006    1970.0
1007    1970.0
1008    2004.0
1009       NaN
1010    1948.0
1011       NaN
1012    1923.0
1013    1956.0
1014    1948.0
1015    2001.0
1016    1996.0
1017    1984.0
1018    1991.0
1019    2005.0
1020    2005.0
1021    2006.0
1022    1957.0
1023    2005.0
1024    1976.0
1025    1980.0
1026    1960.0
1027    2008.0
1028    1941.0
1029    1972.0
1030       NaN
1031    1970.0
1032    1993.0
1033    2002.0
1034    1938.0
1035    1957.0
1036    2008.0
1037    2001.0
1038       NaN
1039    1970.0
1040    1957.0
1041    1966.0
1042    2005.0
1043    1990.0
1044    1981.0
1045    1955.0
1046    2005.0
1047    1996.0
1048    1960.0
1049    1946.0
1050    2007.0
1051    2007.0
1052    1964.0
1053    1957.0
1054    2002.0
1055    1976.0
1056    2005.0
1057    1994.0
1058    2008.0
1059    1977.0
1060    2001.0
1061    1994.0
1062    1945.0
1063    1976.0
1064    1966.0
1065    1996.0
1066    1993.0
1067    1964.0
1068    1973.0
1069    1985.0
1070    1956.0
1071    1968.0
1072    1954.0
1073    1977.0
1074    2006.0
1075    1940.0
1076    1950.0
1077    1969.0
1078    2004.0
1079    1996.0
1080    1971.0
1081    1963.0
1082    2002.0
1083    1964.0
1084    1995.0
1085    1992.0
1086    1973.0
1087    2005.0
1088    2004.0
1089    2005.0
1090    1987.0
1091    1999.0
1092    1925.0
1093    1977.0
1094    1956.0
1095    2006.0
1096       NaN
1097    1987.0
1098    1936.0
1099    1978.0
1100    1930.0
1101    1981.0
1102    1960.0
1103    1954.0
1104    1970.0
1105    1994.0
1106    1990.0
1107    2006.0
1108    2000.0
1109    2004.0
1110    1995.0
1111    1976.0
1112    1957.0
1113    1953.0
1114    1955.0
1115    2007.0
1116    2002.0
1117    1967.0
1118    1958.0
1119    1959.0
1120    1920.0
1121    2005.0
1122    1956.0
1123       NaN
1124    1992.0
1125    1977.0
1126    2007.0
1127    2004.0
1128    2004.0
1129    1980.0
1130    1981.0
1131       NaN
1132    1930.0
1133    1995.0
1134    1997.0
1135    1926.0
1136    1950.0
1137       NaN
1138    1977.0
1139    1972.0
1140    1988.0
1141    1976.0
1142    2006.0
1143       NaN
1144    1941.0
1145    1928.0
1146    1985.0
1147    1941.0
1148    1982.0
1149    1930.0
1150    1950.0
1151    1959.0
1152    1956.0
1153    2002.0
1154    1965.0
1155    1976.0
1156    1965.0
1157    2008.0
1158    2008.0
1159    1974.0
1160    1978.0
1161    1993.0
1162    1968.0
1163    1969.0
1164    1978.0
1165    2009.0
1166    2008.0
1167    2000.0
1168    1935.0
1169    1995.0
1170    1977.0
1171    1958.0
1172    2006.0
1173       NaN
1174    1932.0
1175    1992.0
1176    1984.0
1177    1926.0
1178    1921.0
1179       NaN
1180    1990.0
1181    2008.0
1182    1996.0
1183    1970.0
1184    1963.0
1185    1965.0
1186    1920.0
1187    1994.0
1188    2002.0
1189    1999.0
1190    1975.0
1191    1999.0
1192    1925.0
1193    1999.0
1194    1969.0
1195    2005.0
1196    2006.0
1197    1916.0
1198    2001.0
1199    1974.0
1200    1972.0
1201    1998.0
1202    1960.0
1203    2000.0
1204    1975.0
1205    1990.0
1206    1966.0
1207    2003.0
1208    1980.0
1209    2006.0
1210    1992.0
1211    1988.0
1212    1941.0
1213    1965.0
1214    1962.0
1215    1966.0
1216    1978.0
1217    2009.0
1218       NaN
1219       NaN
1220    1964.0
1221    1968.0
1222    1949.0
1223    1951.0
1224    2004.0
1225    1958.0
1226    2007.0
1227    1992.0
1228    2008.0
1229    1960.0
1230    1977.0
1231    1962.0
1232    1962.0
1233    1959.0
1234       NaN
1235    1914.0
1236    2003.0
1237    2004.0
1238    2005.0
1239    2006.0
1240    2003.0
1241    2007.0
1242    1974.0
1243    2006.0
1244    1931.0
1245    1984.0
1246    2005.0
1247    1976.0
1248    1950.0
1249    1950.0
1250    1968.0
1251    2003.0
1252    1968.0
1253    1974.0
1254    2003.0
1255    1978.0
1256    1994.0
1257       NaN
1258    2005.0
1259    1969.0
1260    1999.0
1261    1956.0
1262    1957.0
1263    1940.0
1264    1998.0
1265    1999.0
1266    1960.0
1267    2009.0
1268    1982.0
1269    1958.0
1270    1979.0
1271    1968.0
1272    1965.0
1273    1959.0
1274    1985.0
1275    1948.0
1276    1972.0
1277    1967.0
1278    2002.0
1279    1980.0
1280    2002.0
1281    1990.0
1282    1977.0
1283       NaN
1284    1969.0
1285    1939.0
1286    1963.0
1287    1964.0
1288    2000.0
1289    2006.0
1290    1964.0
1291    1972.0
1292    1985.0
1293    1976.0
1294    1957.0
1295    1968.0
1296    1963.0
1297    2005.0
1298    2008.0
1299    1959.0
1300    1999.0
1301    1942.0
1302    1994.0
1303    2005.0
1304    2004.0
1305    2006.0
1306    2005.0
1307    2000.0
1308    1948.0
1309    1991.0
1310    1959.0
1311    2005.0
1312    1990.0
1313    1999.0
1314    1956.0
1315    1969.0
1316    2008.0
1317    2006.0
1318    2001.0
1319    1954.0
1320    1957.0
1321    1955.0
1322    1992.0
1323       NaN
1324    2007.0
1325       NaN
1326       NaN
1327    1982.0
1328    1920.0
1329    1998.0
1330    2006.0
1331    1976.0
1332    1958.0